### ISSUE TITLE
FNX-4717 ⁃ [Meta] Search (Awesomebar)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#101]
* Show clipboard shortcut if available
* while typing keyword, show autocomplete
* show recent searches
* enable talk back

currently not included: scan + shortcuts

* [ ] Create search view #141
* [ ] Integrate awesomebar from a-c #142
* [ ] Integrate search suggestions from a-c #143
* [ ] Present clipboard link while field is empty #144
* [ ] Add shortcut pill buttons for `Scan` and `Shortcuts` #145

**Comment by bbinto** [comment]
Discussed with @pocmo to take existing awesomebar component to plug it in for now.

**Comment by Amejia481** [comment]
Awesome bar component-> https://github.com/mozilla-mobile/android-components/blob/master/components/browser/awesomebar/README.md

**Comment by bbinto** [comment]
@Amejia481 - by using the aweseombar component, does autocomplete come for free?

**Comment by pocmo** [comment]
Yes, with the matching `feature` components autocompletion from the static domain lists and history (+ synced) is possible.

**Comment by boek** [comment]
- [ ] Create search view
- [ ] Integrate awesomebar from a-c
- [ ] Integrate search suggestions from a-c
- [ ] Present clipboard link while field is empty
- [ ] Add shortcut pill buttons for `Scan` and `Shortcuts`

# Blocked
- [ ] Show recent searches

**Comment by boek** [comment]
@bbinto What was this bullet point about?: I don't remember seeing it.

> show previous searches based on keywords per search engine

**Comment by bbinto** [comment]
@boek - me neither, let's remove it for now, I think it's sufficient to start with what comes out of the box with a/c

**Comment by sblatz** [comment]
![image](https://user-images.githubusercontent.com/4400286/51050937-62ea8c80-15a0-11e9-887c-15bb042638b5.png)

**Comment by topotropic** [comment]
UX spec: http://mozilla.invisionapp.com/share/VXQ27H3G5ZQ

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

https://docs.google.com/spreadsheets/d/1Mr7jLfIylocpE_Hkhvw62bCB-XLg1KB7bULcJP1-x8w/edit?usp=sharing

**Comment by vesta0** [comment]
All issues listed under this meta have been implemented.
