### ISSUE TITLE
FNX-4774 ⁃ [Meta] Integrate Leanplum SDK

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#107]
Include all "YES" MVP events and deeplinks from this document: https://docs.google.com/spreadsheets/d/1vp3Km7qyyAvkDiUQ3b4lRQUFyA7DQixR8xP1VadA4iw/edit#gid=1742911874

* [x] Get SDK
* [x] Get API key
* [ ] Add documentation to docs/telemetry.md (also related: #981)
* [ ] Request data review from @liuche

**Comment by st3fan** [comment]
I think `S` is a bit optimistic here. It needs to be coordinated with the Leanplum team, keys need to be asked for, testing, etc. Should probably be an `M`.

**Comment by bbinto** [comment]
Include all "YES" MVP events and deeplinks: https://docs.google.com/spreadsheets/d/1vp3Km7qyyAvkDiUQ3b4lRQUFyA7DQixR8xP1VadA4iw/edit#gid=1854399400
