### ISSUE TITLE
FNX-4625 ⁃ Update tab tray design

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10848]
Please update the design to match the Abstract file (you can use Inspect mode to get values) https://share.goabstract.com/1fade20f-700b-4125-baf5-dca4ffd942ee

Please reach out for any questions, feedback or if a value seems off.

* [ ] Add full width separator between tab tray header and first open tab (1dp, light_grey_30)
* [ ] Keep rounded corners at top when expanded full
* [ ] Add white/dark BG for Android bottom bar (currently it has opacity)
* [ ] Update multi-task, private, 3-dot icon and hairline in light mode to ink_20 (#312A65) and in dark mode to violet_50 (#9059FF)
* [ ] reduce opacity of inactive non-private/private icon in light mode to ink_20_48a (#7A312A65)in dark mode to violet_50_48a (#7A9059FF)
* [ ] update new tab button in PBM: add label and update color in light mode to gradient purple_70 (#722291) to violet_80 (#45278D) and in dark mode to gradient purple_50 (#B833E1), violet_50 (#9059FF)
