### ISSUE TITLE
FNX2-13399 ⁃ [Meta] Remove Nightly flag for Edit Logins

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11251]
Edit logins is currently behind a feature flag, but here are the outstanding issues we need to get fixed before it can be un-feature-flagged:

* [x] Basic Edit Logins #9504
* [x] Error states #10172 
* [x] Duplicates/Save criteria #10173 
* [x] Can't easily show password to edit #11250

**Comment by liuche** [comment]
cc @eliserichards, please also add any other items that need to be done before removing the Nightly feature flag!
