### ISSUE TITLE
FNX-4837 ⁃ [Meta] Browser UI + 3 Dot Menu

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#116]
* URL bar at the bottom, door hanger, home icon, menu
* URL collapses
* Swipe up/down to enable/disable Quick action menu
* Include icons of quick action menu (UI only)
* Menu (Help, Settings, Your Library, etc.)
* Talk back implementation

Android components:

* menu component
* toolbar component

Open questions: 

* decide if we should show URL vs title
* GV dependency: resizing web content when you scroll

- - -
* [ ] UI containing the browser and toolbar (#131)
* [ ] URL bar triggers search (#132)
* [ ] Menu button (#133)
* [ ] Collapsing toolbar (#134)
* [ ] a11y (#135)
* [ ] Show URL icon (favicon)

**Comment by Amejia481** [comment]
Toolbar component references:

- https://github.com/mozilla-mobile/android-components/blob/master/components/concept/toolbar/README.md
- https://github.com/mozilla-mobile/android-components/blob/master/components/feature/toolbar/README.md
- https://github.com/mozilla-mobile/android-components/tree/master/samples/toolbar

**Comment by boek** [comment]
- [ ] UI containing the browser and toolbar
- [ ] URL bar triggers search
- [ ] Menu button
- [ ] Collapsing toolbar 
- [ ] a11y

**Comment by Madis0** [comment]
> decide if we should show URL vs title 

The address bar should **never**  show title or favicon.

Neither of those provide any accurate, verifiable information as they are user-generated content, phishers would love to write anything there. 

Better yet, I would recommend using the address bar of Firefox Lite as it is smaller and therefore fits more of the address.

**Comment by andreicristianpetcu** [comment]
Please use the URL. Showing the title is super friendly to phishing.

**Comment by bbinto** [comment]
Our security team probably won't approve this: if displaying title, the risk of spoofing is very high: title is site owner controlled, while domain is something verifiable, e.g. anyone can call their site "Citibank", but there's only one citibank.com

**Comment by lime124** [comment]
betty made do this

**Comment by vesta0** [comment]
@lime124 and @bifleming I am closing this meta as all the related user stories have been completed.

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/15c-w-5zJ07WIkhWkb-LwhkGC-229yzKE7VbuMsPvZAM/edit?usp=sharing
