### ISSUE TITLE
FNX-4852 ⁃ [Meta] Find in Page

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#118]
User Benefit: 
Allow users to search for content within a webpage

As a Fenix user, I want to have a way to search the webpage for content I’m looking for to quicker find the information I’m looking for

* User can input keyword
* User will be shown all occurrences of the keyword 
* User will be able to go back and for on the occurrences
* [ ] Find in page UI (#146)
* [ ] Find in page component (#147)
* [ ] a11y (#148)

**Comment by sblatz** [comment]
Keep in mind accessibility: https://github.com/mozilla-mobile/focus-android/issues/2948

**Comment by boek** [comment]
- [ ] Find in page UI
- [ ] Find in page component
- [ ] Wire it up
- [ ] a11y

**Comment by bbinto** [comment]
Re-opening to include telemetry issue

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/1ybTbu1WRPs6cb96LbwRrHQFE7uCB2H8gYYRUPaRcleM/edit?usp=sharing
