### ISSUE TITLE
[UX] [Meta] Improve usability of Collections

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11967]
## User Story
As a user, I want to organize my online activity in a way that saves me time, is sharable, and is easy to come back to later.

### Acceptance Criteria
* [x] I can quickly save a collection directly from the tabs tray #12856
* [x] I can multi-select on tab tray to save open tabs to a Collection  #10163 
* [x] When I share a collection to another app, the title of the collection appears as the header/subject #12857
* [x] I can hide Collections on my homescreen  #12377

**Comment by yoasif** [comment]
Please see https://github.com/mozilla-mobile/fenix/issues/11463 https://github.com/mozilla-mobile/fenix/issues/6298 and https://github.com/mozilla-mobile/fenix/issues/3804 which all center around some core issues with collections - like the fact that they are copy on load and not well integrated into the tab switching UI. 

Reordering and moving tabs could be accomplished with a tab group like UI as suggested https://github.com/mozilla-mobile/fenix/issues/10372

>I am reminded that I can create a collection to organize my tabs when I have more than x tabs open.

If collections are integrated into the tab tray, a reminder can be made contextually in that UI.

**Comment by sheikh-azharuddin** [comment]
Unless collections are backup/synced to cloud ,they are of no use...we spent days to collect them and then when you factory reset phone or reinstall app everything is lost!
So how is this better than top sites??

Regarding collection reorder we can have something like edge...

![Screenshot_20200625-225210_Edge](https://user-images.githubusercontent.com/58127841/85768370-79d75d00-b708-11ea-9d53-43dd1a61b73f.png)

![Screenshot_20200625-225221_Edge](https://user-images.githubusercontent.com/58127841/85768409-8491f200-b708-11ea-9477-9d253082f43e.png)

**Comment by Dunexus** [comment]
Based on the recent discussions, i think it is really unclear what collections are and where they fit between top sites, bookmarks and tabs.
It will be necessary for UX to clarify this point to improve discoverability.

**Comment by vesta0** [comment]
Thanks @yoasif I am reviewing all issues with the `feature:collections` label and deciding what makes sense for our next iteration so I will definitely look at your suggestions!

@sheikh-azharuddin we are working on backing up Collections for SYNC users!

@Dunexus that's a great call out, we are thinking about this.

**Comment by vesta0** [comment]
The enhacements that we wanted to address in this meta have been implemented. Thanks team!
