### ISSUE TITLE
[Meta] Optimize the search experience when starting a new search

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12064]
### User Story
As a user, I want the most useful and relevant information surfaced to me when I start a new search, so I can search faster and easier. 

User problems:

* Given recent changes, the new search screen is now completely blank. Let's re-think how/if alternative search engine options should be surfaced on the new search page
* We should make it fast and easy for users to search for what they need or access saved/useful content such as frequently visited sites, recent searches, or recently saved content.

We should look at optimizing these 3 surfaces:

-Search screen when user first opens a new search
-Search screen once user starts typing
-Search screen when user edits/erases what they typed

User flow design: 
https://share.goabstract.com/602c3610-3b82-4c13-8b33-3852f8d699be?collectionLayerId=0b13bc02-eec3-4f30-8225-47f13e171923&mode=design

### Acceptance Criteria
* [x] When manually opened, the New Tab Page should be ready for quick search #13052 
* [x] When the New Tab Page has the keyboard open, the keyboard should be easy to dismiss #13053
* [x] Remove search suggestions after erasing #12570
* [x] Renaming "Shortcuts" to "Search engines" #12571

**Comment by vesta0** [comment]
This work has been completed!
