### ISSUE TITLE
FNX3-22123 ⁃ [meta] Faster TC builds: android-components worker type, caching, doing less work in tasks, etc

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13555]
We're scheduling tasks for every module, and every one of those tasks performs a full repository fetch, and a clean build. Results of both of these operations could be cached, and re-used as much as possible which should help avoid doing the most costly part of each of those tasks.

For caching to make sense, we'd need to switch to our own worker type. Currently we're running on a very large pool of workers of generic type `github-worker`, which makes cache hits unlikely. It might also help to have a single "root" task that all others depend on, which will populate the cache.

Relevant work:

* [ ] #1461 - Use in-tree Dockerfile
* [ ] #1462 - Use docker-worker Taskcluster caches
* [x] https://github.com/mozilla-mobile/android-components/pull/1588 - Use mobile-{1,3}-decision worker types
* [x] https://github.com/mozilla-mobile/android-components/pull/1614 - Run lint for a single variant
* [x] https://github.com/mozilla-mobile/android-components/issues/1293 - Build variants in parallel; Switch to `android-components-g` worker type
* [ ] https://github.com/mozilla-mobile/android-components/issues/638 - Evaluate Gradle Enterprise
* [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1517571 - Higher capacity for the `android-components-g` worker type

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Some thoughts:

  * We do cache a bunch of things (e.g. dependencies) in the Docker image. However this requires us to re-build the Docker image every now and then. That's a manual process currently.
  * Now without Travis the turn-around time has gone down to 25 minutes (from about 40).
  * The bottleneck right now is sample-browser (25 minutes) while most other component tasks resolve in less than 10 minutes. This is mostly because of the variants. Building the sample app variants in parallel would speed things up.
  * Gradle allows to setup a remote build cache server (See #638). CI builds save build snapshots in the cache and other CI tasks as well as developers locally can use this cache to avoid re-building things that have already been build (e.g. most of the component tree).

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

> performs a full repository fetch

We do have a checkout in the Docker image. Fetching the changes of the PR is only a tiny fraction of the task run time.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

This reminds me.. the last time I looked into taskcluster caches I read something about only one task at a time being able to use the cache. I wonder if this still applies.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Even without caching we may want to use our own worker-type. I was looking into what we get guaranteed (e.g. available memory) to tweak some build flags. But with the github-worker we basically get whatever. According to the taskcluster team with a dedicated worker type we can pick an AWS instance type and how many tasks we want to run in parallel per instance. Picking something more powerful could speed up things significantly.

**Comment by data-sync-user** [comment]
➤ Nick Alexander commented:

>     * We do cache a bunch of things (e.g. dependencies) in the Docker image. However this requires us to re-build the Docker image every now and then. That's a manual process currently.

I've filed #1461 to track this.

**Comment by data-sync-user** [comment]
➤ Nick Alexander commented:

> Even without caching we may want to use our own worker-type. I was looking into what we get guaranteed (e.g. available memory) to tweak some build flags. But with the github-worker we basically get whatever. According to the taskcluster team with a dedicated worker type we can pick an AWS instance type and how many tasks we want to run in parallel per instance. Picking something more powerful could speed up things significantly.

Yes, you want this immediately.  The reason isn't so much the AWS details, it's getting out of the github-worker pool.  That means you can start exploiting docker-worker caches, which are per-worker type.  Let's prioritize this right now: https://bugzilla.mozilla.org/show_bug.cgi?id=1509538.

**Comment by data-sync-user** [comment]
➤ Grisha Kruglov commented:

Another benefit (albeit rather small, I imagine) of having our own worker-type is ability to configure expiration time for the downloaded Docker images. IIRC they currently expire every two hours (if unused), which means we're downloading the docker image quite often.
