### ISSUE TITLE
FNX3-22186 ⁃ Meta: Screenshots API

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13608]
### Description
-Options to take a screenshot of whole page, viewed area, a selection
-Option to save screenshot to Photos folder and screenshots folder in Fenix Library

### Target
* https://github.com/mozilla-mobile/fenix/issues/89

### Tasks
* [ ] #498 - Engine: Add support for taking screenshots 
* [ ] #1382  - Engine: Add support for capturing thumbnails

### Dependencies
* [ ] [Bug 1462018 - GeckoView: Add support for taking screenshot of web content (for tab thumbnail tray)](https://bugzilla.mozilla.org/show_bug.cgi?id=1462018)

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Waiting for UX mocks  ( https://github.com/mozilla-mobile/fenix/issues/183 )

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

GV support for taking viewport screenshots (for page thumbnails in tab switcher UI) has landed (bug 1462018 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1462018 )). Full page shots (bug 1530967 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1530967 )) is still planned but it will be more work.
