### ISSUE TITLE
FNX3-22195 ⁃ Meta: Migrate to AndroidX libraries

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13624]
# Description
We want to migrate from support libraries to the new [AndroidX libraries](https://developer.android.com/jetpack/androidx/). That's where all the new features get implemented.

Switching requires a careful migration process where the downstream app projects will have to migrate first and then upstream libraries can follow. If one library switches to AndroidX it forces all its downstream consumers to make the switch too.

Downstream projects can use [Jetifier](https://developer.android.com/studio/command-line/jetifier) to rewrite their dependencies using support libraries to use AndroidX instead (at build time). This allows apps to make the switch before all their dependencies have done that. While Jetifier is helpful for the migration it's also something we want to get rid of as soon as possible: It breaks [gradle composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) (which we really really want) and [it has bugs](https://github.com/mozilla-mobile/reference-browser/issues/487#issuecomment-458044712).

A primary goal of this migration is to clear the path for _Fenix_ / _Reference Browser_ to _Android Components_ to _GeckoView_ and _Application Services_ (without using Jetifier).

# Step 1: Migrate app projects
## P1
We should not migrate any libraries and force a migration until those projects have migrated first.

* [x] Fenix
* [x] Firefox for Fire TV
  * [x] https://github.com/mozilla-mobile/firefox-tv/issues/1398 -  _Move support libraries to androidx_
* [x] Firefox for Echo Show
  * [x] https://github.com/mozilla-mobile/firefox-echo-show/issues/72 - _Upgrade to Android SDK 28_
  * [x] https://github.com/mozilla-mobile/firefox-echo-show/issues/217 - _Migrate from support libraries to AndroidX_
* [x] Reference Browser
* [x] Lockbox
* [x] Firefox Reality

## P2
Migrating those projects before migrating is a "nice-to-have" but this may not block starting to migrate upstream libraries.

* [x] Firefox Focus
  * [x] https://github.com/mozilla-mobile/focus-android/pull/4284
* [x] Firefox ScreenshotGo
* [x] Firefox Lite (Rocket)
  * [x] https://github.com/mozilla-tw/FirefoxLite/issues/3137 - _Migrate from support libraries to AndroidX_

## P3
Those projects are either not actively developed or are not actively updating Android Components or are very light consumers of support libraries (e.g. React Native apps).

* [ ] Notes by Firefox
* [ ] Send by Firefox

# Step 2: Migrate Android Components
* [x] https://github.com/mozilla-mobile/android-components/issues/842 - Migrate Android Components to use AndroidX libraries. Since some components are only used by projects that are already migrated this process can happen on a component-by-component level.

# Step 3: Migrate upstream libraries
* [ ] Migrate GeckoView to use AndroidX [(Bug 1553459)](https://bugzilla.mozilla.org/show_bug.cgi?id=1553459)
* [ ] Migrate application-services libraries to use AndroidX

# Step 4: Update third-party dependencies
Our projects (apps and libraries) may have third-party dependencies that depend on support libraries. In order to be able to get rid of Jetifier we will need to migrate to versions of those dependencies that use AndroidX. Multiple third-party libraries are either publishing two artifacts (support libraries / AndroidX) during the migration time or have published a new major version using AndroidX.

* (TBD; This requires analyzing of our dependencies)

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Interesting article:
https://proandroiddev.com/the-state-of-jetification-in-early-2019-plus-a-bonus-gradle-plugin-aac5854af910

This is a gradle plugin that can check the dependencies of a project and tell you if you can drop jetifier or if some dependencies still depend on the old support libraries. That should be helpful to determine what we are missing (Step 4 above).
https://github.com/plnice/can-i-drop-jetifier/

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Woot! I just read that jetifier has a reverse mode too:
https://ncorti.com/blog/jetifier-reverse

This means we could migrate and apps that do not want to migrate yet can use Jetifier reverse mode to continue to use the old support libraries. ... but:

From the article above:
> Unfortunately, the reverse mode is not integrated into the Android Gradle Plugin and there is no property to set to enable it. The only way to run it is to use the standalone version.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Another funky option would be to:

  * Migrate AC to use AndroidX
  * Run reverse mode on the AAR before publishing.

Result:

  * The local checkout uses AndroidX and we can get one step closer to using Gradle composite builds
  * The shipping AARs still use the old support libraries.

It's risky to ship something else than what you build locally though.. 😀

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

According to can-i-drop-jetifier only the GeckoView dependency requires jetifier. That would be nice!

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Filed GeckoView bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1553459

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Migration of Focus is in progress and migration of Firefox Lite is planned.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

Follow-up to get rid of jetifier: #8459.
