### ISSUE TITLE
Investigate and remove feature flag for Synced Tabs in Tabs Tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#13892]
We added a feature flag for this change and this ticket is to track the removal of the flag to let it ride the trains.

Tracking feature: https://github.com/mozilla-mobile/fenix/issues/12287

### Potential Blockers
 - [ ] [#14117][14117] - Show Synced Tabs in a separate tab on the tabs tray
 - [ ] [#13905][13905] - Selected tab is not seen when Synced Tabs is in Tabs Tray 
 - [ ] [#14307][14307] - New option sync tabs is not correctly displayed
 - [ ] [#14007][14007] - Synced tabs in tabs tray can only be viewed if there's at least 1 tab open

[13905]: https://github.com/mozilla-mobile/fenix/issues/13905
[14307]: https://github.com/mozilla-mobile/fenix/issues/14307
[14007]: https://github.com/mozilla-mobile/fenix/issues/14007
[14117]: https://github.com/mozilla-mobile/fenix/issues/14117

**Comment by liuche** [comment]
Also related #14294

**Comment by jonalmeida** [comment]
> Also related #14294 #12870 (please feel free to dupe!)

Both of these have the same root cause that require https://github.com/mozilla/application-services/issues/3373 but I do not think it's a blocker. We _need_ to fix it though because it looks quite bad otherwise.

Happy to make it a blocker if we feel otherwise.

**Comment by liuche** [comment]
Private mode shows white on white text #14407

**Comment by jonalmeida** [comment]
I added #14117 to the list, which if completed, would invalidate the other bugs.

**Comment by jonalmeida** [comment]
I'm going to use this ticket to remove the feature flag for synced tabs appended to the normal tabs as well as the code there to make it easier for refactoring the tabs tray.
