### ISSUE TITLE
Tracking build flags for non-free dependencies

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#15705]
From https://github.com/mozilla-mobile/fenix/issues/162#issuecomment-674378939,

- [x] Remove play-services-oss-licenses library:
  - [x] PR done #13767
  - [x] PR approved
  - [x] PR merged

- [ ] Build flag for mozilla-lib-push-firebase
  - [x] PR done #13857
  - [ ] PR approved
  - [ ] PR merged

- [ ] Build flag for leanplum
  - [ ] PR done
  - [ ] PR approved
  - [ ] PR merged

- [ ] Build flag for google-ads-id
  - [ ] PR done
  - [ ] PR approved
  - [ ] PR merged

- [ ] Build flag for play-services:core
  - [ ] PR done
  - [ ] PR approved
  - [ ] PR merged

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7887)

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813270

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
