### ISSUE TITLE
[Meta] Gestures

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#176]
We want to support the following gestures: 

**Long press to select and reveal actions**
Works on cards, list items and web content, for example

* [x] long press on tab on home to enter selection mode (implemented)
* [x] long press on bookmark item to enter selection mode (implemented)
* [x] long press on history item to enter selection mode (implemented)
* [x] long press on text, images, links to get additional actions (context menu) (implemented)

**Long press to quickly navigate to a view**
Works on selected UI icons to get quicker to a view, for example

* [x] long press on multi-select icon to open a new tab (P2) (implemented)
* [x] long press on back/forward navigation arrow in menu to open a tabs history (P3, #1048 )
* [x] long press on site lock to open Site permissions in settings (P3)

**Pull to refresh**

* [x] https://github.com/mozilla-mobile/fenix/issues/3262
* [ ] https://github.com/mozilla-mobile/fenix/issues/9766
Works on views that can update content, for example
* [ ] pull down on a site to refresh the content (P1)
* [x] pull down on bookmarks to start sync (P2, #2165) (implemented)
* [x] pull down on history to start sync (P2, #2165) (implemented)

**Swipe left/right to delete**
Works on cards and list items, for example

* [x] swipe left/right on a card/tab on home to delete (implemented)
* [x] swipe left/right on a bookmark entry to delete (P3, #12551)
* [ ] swipe left/right on a history entry to delete (P3, #12610)
When people start swiping on a card or list item, the action is revealed and people can either pull through to delete or stop and keep the item.

**Swipe left/right to navigate**

* [ ] swipe left/right on site to go backward/forward in tab history (P2, #12327)
* [x] swipe left/right on browser URL bar to go to previous/next open tab (P2) https://github.com/mozilla-mobile/fenix/issues/3481
* [ ] consider swipe up/down (depending on bottom or top app bar) to view tab tray / home (#11862)

(priority labels are used to communicate the relative importance of the gesture)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9481)

**Comment by bbinto** [comment]
Not clear what that entails, could you please provide more info.

**Comment by shorlander** [comment]
Figure out swipe gestures for list items. E.g. swipe to close, swipe to send, etc.

**Comment by yoasif** [comment]
See #396.

**Comment by lime124** [comment]
adding #543

**Comment by boek** [comment]
adding #504

**Comment by lime124** [comment]
https://github.com/mozilla-mobile/android-components/issues/1824

Pull to refresh

**Comment by lime124** [comment]
#425

**Comment by lime124** [comment]
there cannot be a swipe-up from bottom gesture #1021

**Comment by vesta0** [comment]
#1254 Adding swipe to go back to a website and forward to a website.

**Comment by Lululalu** [comment]
I would like to suggest a gesture to switch between tabs by swiping on the address bar, like chrome does. It 
is very intuitive e make mobile browsing much easier and quicker.

**Comment by cpeterso** [comment]
> #1254 Adding swipe to go back to a website and forward to a website.

GV bug for iOS-like back/forward navigation gestures: https://bugzilla.mozilla.org/show_bug.cgi?id=1509249

**Comment by sv-ohorvath** [comment]
Suggested a new gesture: #2165

**Comment by NotWoods** [comment]
The new back gesture in Android Q will automatically add swipe to go back into the app (from either side of the screen), but its probably still worth adding support for older Android versions and supporting forward swipes.

**Comment by ChristianCiach** [comment]
Switching tabs by swiping is absolutely essentials to me and people I know. I don't exaggerate when I say that this is the **only** reason I just cannot use the previous Firefox. Currently, switching tabs requires at least three taps. That is just too cumbersome.

**Comment by willfs84** [comment]
The accidental swipe-up from bottom issue should not be dismissed, every week I see someone mention this either in Play Store reviews, on reddit, Twitter etc. It's not only an issue for phones that use the swipe-up to go Home gesture, it's for 100% of phones because it happens when users are trying to scroll down a webpage. 2 users in this reddit thread from today mentioned it... https://www.reddit.com/r/firefox/comments/cx2tgj/lets_share_opinions_on_firefox_preview_on_android/   Please see my original post here for more details https://github.com/mozilla-mobile/fenix/issues/1021

**Comment by djc** [comment]
Long-press back button is definitely something I miss on a regular basis.

**Comment by madb1lly** [comment]
>  long press on back/forward navigation arrow in menu to open history (P3)
I think many people are expecting long press on back or forward to open the history _for that specific tab_, like in Fennec. The overall history page is not much use for tab hoarders like me ;)

**Comment by ghoppaccia** [comment]
And also swipe to go backward/forward in tab history. Is a must have feature to me, the only browser doing it right ATM is Safari on IOS. Having this in Firefox would be great also to be ahead of other browsers.

**Comment by yoasif** [comment]
I opened https://github.com/mozilla-mobile/fenix/issues/10374 which conflicts with:

> long press on multi-select icon to open a new tab (P2)

so I hope it can be reevaluated, given that a competing browser supports https://github.com/mozilla-mobile/fenix/issues/10374

**Comment by yoasif** [comment]
Still interest in:

> swipe left/right on browser URL bar to go to previous/next open tab (P2)

https://www.reddit.com/r/Android/comments/gy8ac5/the_brave_web_browser_is_hijacking_links_and/ft9l71i/

>I've grown so accustomed to switching tabs by swiping on the URL bar that I can't use Firefox for mobile...

**Comment by anmol257** [comment]
New Gesture Suggestion
If a user accidentally clicks on a link & wants to stop it from loading he can **double-tap**
     Also any update by when gestures will be included in fenix?

**Comment by person808** [comment]
@anmol257 No specific ETA for when each gesture will be in Fenix. Right now the gestures marked P2 (priority 2) are what I'm currently working on. Some gestures will take more time to implement and polish than others but we are aware that many users want them.

**Comment by carallo** [comment]
> @anmol257 No specific ETA for when each gesture will be in Fenix. Right now the gestures marked P2 (priority 2) are what I'm currently working on. Some gestures will take more time to implement and polish than others but we are aware that many users want them.

Are you planning of implementing the swipe to go back/forward in history? Is just so incredibly natural and pleasuring to use. Ever tried Safari on an iPhone?

**Comment by person808** [comment]
@carallo I believe that is what the first item under "Swipe left/right to navigate" is referring to. That is something I plan to look into but it will likely require UX work and some investigation into how it would be implemented, so no specifics on when it would be done.

**Comment by carallo** [comment]
> @carallo I believe that is what the first item under "Swipe left/right to navigate" is referring to. That is something I plan to look into but it will likely require UX work and some investigation into how it would be implemented, so no specifics on when it would be done.

Thanks, will keep an eye on the issue when it will opened. I have some advices, such as for the preview of the page you are moving to (Safari implementation vs Chrome overscroll).

**Comment by cousteaulecommandant** [comment]
May I add or suggest "swipe URL bar down/up to hide it"?  (i.e., swipe it towards the edge, as opposed to swiping it away from the edge as suggested in #11862.) Sometimes the URL bar seems to refuse to hide.

**Comment by MarjaE2** [comment]
Once it's possible to log in, it'd be nice to be able to navigate without swipes, gestures, and the rest.

**Comment by opusforlife2** [comment]
What happened? Some other issue is being marked to track this?
