### ISSUE TITLE
[Meta] UX changes for three-dot menus

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17796]
Breaking this out of #14320 for tracking purposes since there's a lot of discussion on that thread.

**This work should be behind a feature flag**

UX Figma designs (bottom right, labeled "Final designs"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

- [x] Reordering for main menu: https://github.com/mozilla-mobile/fenix/issues/17771
- [x] Navigation, share, refresh on main menu: #17802
- [x] Add menu icons back: #17872
- [x] Add open in app back: #18461
- [ ] Expanding/scrolling (incl. top toolbar vs bottom toolbar): https://github.com/mozilla-mobile/fenix/issues/17772
- [ ] New tab menu (reordering and nav): https://github.com/mozilla-mobile/fenix/issues/17770
- [ ] Add/Edit bookmark button: #17797
- [ ] Sign in to sync (depends on sync tabs decision in tabs tray, #14969 and #14117): https://github.com/mozilla-mobile/fenix/issues/17798
- [x] Extensions submenu: #17799
- [ ] Request desktop site from new tab: #17800
- [x] Change reader view "Appearance" menu item: https://github.com/mozilla-mobile/fenix/issues/17971
- [ ] Remove feature flag: #17870

**UI Tests**
- [ ] New tab menu: #17840 - assigned to QA testing team (irios) 
- [ ] Main menu: #17979 - assigned to QA testing team (irios)

**Open question:** how will this work be affected by the Nimbus bookmarks test? Will the work overlap?
 -  We _think_ the goal is more to test the platform, so it might be worth it to keep the experiment. The ultimate decision can be made by Vesta 

---
Other work:
* This should be implemented behind a feature flag, which can be removed once it's finished (added in #17838)
* Make sure we have l10n translations
* Remove all of the actual icon resources that are no longer needed
* Accessibility _must_ be addressed in this redesign (e.g. Talkback, labels)
* Add/remove telemetry where needed

**Comment by eliserichards** [comment]
Additional bugs/stories: 
- [x] Persist open in app in main menu: #18461 
- [x] Report site issues on Nightly/Debug: https://github.com/mozilla-mobile/fenix/issues/18032
- [ ] Margins for main navigation #18591 
- [ ]

**Comment by USvsTHEM** [comment]
remove this foolishness yall fumbled
