### ISSUE TITLE
Consistent naming and conventions in the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19002]
This ticket is for agreeing on some naming consistencies and conventions that are easier to do with fewer pieces of the tabs tray code moving around every day. 😄 

Looking for feedback from @rocketsroger and @codrut-topliceanu since we all worked on the initial refactoring.

## Actionable tasks
- [ ] Rename all 'store' references to their specific type:
  - If it's a `TabsTrayStore` then: `store` -> `tabsTrayStore`
  - If it's a `BrowserStore` then: `store` -> `browserStore`
- [x] Remove `TrayItem` interface. (https://github.com/mozilla-mobile/fenix/pull/19460)
  - This was added initially for type-checking, but we don't have any usages of it any more.
- [x] Rename "list" naming from classes. (https://github.com/mozilla-mobile/fenix/pull/19460)
  - The name is inconsistent since not all our pager items are limited to being "lists". 
  - How about `page`? This is consistent with the Android API.
- [x] Move `TabsTrayViewHolder` to the `browser` sub-package. (https://github.com/mozilla-mobile/fenix/pull/19460)
  - Rename: `TabsTrayViewHolder` -> `AbstractTrayViewHolder`
- [x] Remove `configuration` from `NormalBrowserTrayList`/`PrivateBrowserTrayList` (https://github.com/mozilla-mobile/fenix/pull/19460)
  - We created this with the idea that more configs would need to go in there to separate the two types, but we have an existing pattern of settings the store/controller in the parent viewholder. We can also set the configuration from there as well. TL;DR convert `abstract val` in `BaseBrowserTrayList` to `lateinit var`.

## Open questions
- [x] ~Do we feel about the feature "Binding" naming?~ Upstreaming to AC: https://github.com/mozilla-mobile/android-components/issues/10050
- Should we introduce a "View" class for all the UI? For other components in Fenix, we have a concept of a view class to follow the architecture. In the tabs tray, we didn't really need it at the time. It made it easier to access certain lifecycle  code and avoid boilerplate things as we needed to iterate quickly. I have no strong feelings for adding a `TabsTrayView`, although I would like to avoid any single class from becoming a dumping ground for any and all code.
- Should something need to be an interactor or a controller? We have controllers and interactors used almost interchangeable (this is by my fault!) so how would we feel about moving things around to follow a better convention?

**Comment by codrut-topliceanu** [comment]
@jonalmeida @rocketsroger I have a proposal for your consideration.

I think it would be really useful to have an UML diagram for the architecture of the tabs tray re-write. I've worked on one for myself, as I was having trouble keeping up with all the names, but it's very inaccurate, plus the work on the tabsTray continued to change things.

So maybe when we have things "locked" in place for the tabs tray we could take a look at implementing something like this, what do you think?

**Comment by jonalmeida** [comment]
This is a great idea! I'm not sure where one would live though. Maybe it can be broken into parts that we can add as ASCII art in the kdocs. Keeping a diagram that is linked to an image in a different place will go out of sync quickly.

I think we should do this when we've settled with the naming correction.

**Comment by jonalmeida** [comment]
We've solved everything here except for the ascii docs, but that should be okay because we're simplifying this with compose.
