### ISSUE TITLE
FNX-493 ⁃ [Meta] Progressive Web Application (PWA)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#204]
**User Story:**
As a user, I want to install a PWA of a site (when available) on my homescreen so I can experience an app-like interaction with that site. 

This Epic is about implementing the classic shortcut based PWA support for Fenix, similar to Fennec implementation.

A-C work tracked [here](https://github.com/orgs/mozilla-mobile/projects/13)

InVision: https://mozilla.invisionapp.com/share/RGSCJEGJM8T

### Acceptance Criteria
* [x] #768 Know when a site is available as a PWA 
* [x] #778 Install a PWA to my home screen 
* [x] #770 Open installed PWAs in fullscreen / standalone mode
* [x] #779 Refresh the currently displayed page in a PWA
* [x] #777 External URLs in a PWA to open in a custom tab
* [x] #771 Web Push Notifications
* [x] #769 Use PWAs while offline 
* [x] #780 Share from my installed PWA to other installed (native) apps

**Comment by bbinto** [comment]
@vesta0 to meet with GeckoView team and @st3fan to discuss next steps.

I'm looking for a basic implementation. Happy to assist and chime in as well.

**Comment by vesta0** [comment]
Discussed concept with @brampitoyo. Will review and discuss preliminary UX designs/user flow next week.

**Comment by jacktose** [comment]
Addition to the user story for me: I'd like the app icon to also be available in the app drawer. Chrome currently does this and Fennec does not.

**Comment by liuche** [comment]
@vesta0 these are done by Design, so we discussed moving them to a section in the Feature Backlog for you to prioritize!

**Comment by ekager** [comment]
Since this list has been completed, we are going to remove the feature flag now!
