### ISSUE TITLE
[Meta] Composify the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21318]
To avoid breaking everything at once, we can incrementally introduce Compose into our tabs tray by following this order of converting the code:

1. [x] https://github.com/mozilla-mobile/android-components/issues/11012 
     - Update TabsFeature to pass in TabSessionState instead of tabstray's `Tab`.
1. [x] https://github.com/mozilla-mobile/fenix/issues/21894 
     - Individual tab viewholders: `GridViewHolder`, `ListViewHolder`.
2. [ ] https://github.com/mozilla-mobile/fenix/issues/21896
     - Gesture support - how to support swiping to delete by horizontal and vertical directions, see `TabsTouchHelper`
3. [x] https://github.com/mozilla-mobile/fenix/issues/21897 
     - Inactive tab list - see `InactiveTabsAdapter` and it's viewholders.
4. [x] https://github.com/mozilla-mobile/fenix/issues/21898 
     - Group lists - this is where gesture support can help us too with vertical swiping.
5. [ ] https://github.com/mozilla-mobile/fenix/issues/21899 
     - Browser lists - see `NormalBrowserTrayList`, `PrivateBrowserTrayList`, `AbstractBrowserTrayList`.
6. [x] https://github.com/mozilla-mobile/fenix/issues/21900 
     - Synced Tabs list - `SyncedTabsTrayLayout`, `SyncedTabsAdapter`
     - We can do this async; doesn't have to wait for the normal/private tab list.
6. [ ] https://github.com/mozilla-mobile/fenix/issues/21901 
     - Normal/Private page list - `NormalBrowserPageViewHolder`, `PrivateBrowserPageViewHolder`, `SyncedTabsPageViewHolder`
7. [x] https://github.com/mozilla-mobile/fenix/issues/25891
8. [ ] https://github.com/mozilla-mobile/fenix/issues/26131
9. [ ] ⚠️ **Profile tabs tray performance before/after a full Compose re-write OR during each incremental step.**
    - Reading reference: https://engineering.premise.com/measuring-render-performance-with-jetpack-compose-c0bf5814933
    - There is an interesting analysis on perf for Compose in Pocket here: https://github.com/mozilla-mobile/fenix/pull/22067
10. [x] https://github.com/mozilla-mobile/fenix/issues/26087
11. [ ] https://github.com/mozilla-mobile/fenix/issues/26476

_(file individual tickets and link them here)_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17892)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810775

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
