### ISSUE TITLE
[meta] Add benchmarks for page load use cases

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21876]
_We probably won't implement this anytime soon so this issue is likely just a placeholder to remind us of the different scenarios we need to think about._

Our current page load testing sends load url events to Gecko directly. We should write some page load benchmarks that use the UI. From https://github.com/mozilla-mobile/fenix/issues/21530#issuecomment-938954112, I've identified a few cases with slightly different code execution paths:
- [ ] Entering a URL (or autocompleted URL) from the search screen
- [ ] Entering a search from the search screen
- [ ] Clicking an autocompleted search result (probably the same as above)
- [ ] ^ These cases but a user needs to create a new engine session to do them (as opposed to re-using a tab)
- [ ] ^ These cases but page includes a redirect BZ-1734916
- [ ] ? Custom tabs, other contexts I'm not thinking about

**Comment by mcomella** [comment]
Replacing with this more generic meta: https://github.com/mozilla-mobile/fenix/issues/22302
