### ISSUE TITLE
FNX-5512 ⁃ [Product Quality] Main Browser Toolbar - Checklist (Ongoing)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2203]
## **Feature Level Checklist for Main browser toolbar** 
This is an ongoing list for product quality related bugs for this feature/component. Any non-blocking UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Please see examples of what is considered essential and non-essential UX bugs. Blocking UX bugs should be filed separately and triaged by product. Items in this list that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed)

- - -
**Checklist**

* [x] **Toolbar:** Tabs and Options menu are not equally spaced on toolbar
https://github.com/mozilla-mobile/fenix/issues/1469
Spec: https://mozilla.invisionapp.com/d/main#/console/16853870/358780699/preview

[Reporter: AmyYLee] [Date: 05/09/19]

* [x] **Toolbar:** Missing separator between QAB and Main Toolbar
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **Toolbar:** Missing 1dp shadow
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **Toolbar:** Not enough space between QAB and Main Toolbar
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **Toolbar:** Toolbar should be 56dp tall
[Reporter: AmyYLee] [Date: 05/01/19]
* [ ] **Toolbar:** Does not have a transition between page and start screen (tab switching)
Please reference https://github.com/mozilla-mobile/fenix/issues/1289 
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **Quick Action Bar:** Incorrectly hides with swipe (disappears completely - should still have handle visible)
* [x] **Quick Action Bar:**  (Sessions and Menu) should be 48dp x 48dp
[Reporter: AmyYLee] [Date: 05/01/19]
* [ ] **Quick Action Bar:** Does not hide correctly while scrolling - QAB when expanded should go into collapsed version before it disappears complete with the search bar. 
[Quick Action Bar Spec](https://mozilla.invisionapp.com/share/K3RKVUJUG5B#/screens)
[Quick Action Bar - Reference.mp4.zip](https://github.com/mozilla-mobile/fenix/files/3135936/Quick.Action.Bar.-.Reference.mp4.zip)
[Reporter: AmyYLee] [Date: 05/01/19]
[Edit: Sawyer] [Date: 08/01/19]: I think we should **hold off** on this one for now since it will be fixed once we have a dynamic toolbar again and is very difficult to implement with the current solution.
* [x] **App Menu:** Icons should be vertically centered in the bottom row
https://github.com/mozilla-mobile/fenix/issues/2175
[Reporter: AmyYLee] [Date: 05/01/19]
[[Fixed](https://github.com/mozilla-mobile/android-components/pull/3991)] [Date: 08/01/19] 
* [x] **App Menu:** Bottom nav buttons should be 56dp to align with the Main Toolbar
[Reporter: AmyYLee] [Date: 05/01/19]
[[Fixed](https://github.com/mozilla-mobile/android-components/pull/3991)] [Date: 08/01/19] 
* [x] **App Menu:** Has an unneeded separator between "Library" and "Desktop Site"
[Reporter: AmyYLee] [Date: 05/01/19]
* [ ] **App Menu:** Left and Right margins should be 16dp
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **App Menu:** Space between Icon and Label should be 12dp
[Reporter: AmyYLee] [Date: 05/01/19]
[[Fixed](https://github.com/mozilla-mobile/fenix/pull/4465)] [Date: 08/01/19] 
* [x] **App Menu:** "Desktop Site" toggle is green and not the Accent color
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **App Menu:** Should animate from origin and not the top
https://github.com/mozilla-mobile/fenix/issues/343
* [ ] **Search:** Does not have a transition for searching / entering address from toolbar 
[Reporter: AmyYLee] [Date: 05/01/19]
* [x] **Find in Page:** Needs 1dp drop-shadow
Reference bug https://github.com/mozilla-mobile/fenix/issues/2140
[Reporter: AmyYLee] [Date: 05/03/19]
[[Fixed](https://github.com/mozilla-mobile/fenix/pull/4465)] [Date: 08/01/19]

**Comment by sblatz** [comment]
Let's timebox this to a 3 for this sprint to address the most critical issues.

**Comment by sblatz** [comment]
> Quick Action Bar: Does not hide correctly while scrolling 
I tried to address this, but it will require AC exposing the `GeckoEngineDidScroll` callback. Honestly, I think we should punt on this item **since it will be fixed when we bring back the dynamic toolbar**.

**Comment by sblatz** [comment]
Find in page bar with drop shadow

<img width="350" alt="Screen Shot 2019-07-31 at 9 46 48 AM" src="https://user-images.githubusercontent.com/4400286/62231177-5715ba80-b378-11e9-935f-bbd1cb06b08e.png">

**Comment by sblatz** [comment]
Bottom menu items are now perfectly centered and the toolbar line matches the "divider line" of the menu:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/62310403-4a5b9a00-b43e-11e9-8b1d-56b4938fde26.png">

**Comment by liuche** [comment]
Waiting on some AC updates.

**Comment by sblatz** [comment]
The fixes I worked on are done. The only items left are now animations and the quick action sheet not collapsing which will be fixed when we bring back the dynamic toolbar.

**Comment by sblatz** [comment]
Closing and leaving the rest of the items for #4538.
