### ISSUE TITLE
FNX-512 ⁃ [Product Quality] Search - Checklist (Ongoing)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2210]
**Feature Level Checklist for Main browser toolbar**

This is an ongoing list for product quality related bugs for this feature/component. Any non-blocking UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Please see examples of what is considered essential and non-essential UX bugs. Blocking UX bugs should be filed separately and triaged by product. Items in this list that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed)

- - -
**Checklist**

* [x] - Search Field should be 40dp tall
#3773
* [x] - Search Field should have 8dp top, left, and right margins
https://github.com/mozilla-mobile/fenix/issues/2186
* [x] - Search Field Icon should be 24dp
#3773
* [x] - Search Field Icon and Label should have 12dp spacing
#3773
* [x] - Search Results should have 16dp left and right margins
https://github.com/mozilla-mobile/android-components/pull/3575
* [x] - Search Results background is white should be "Foundation" color
#3773
* [x] - Search Result Label and Status text should have 16dp line-height (from baseline to baseline)
https://github.com/mozilla-mobile/android-components/pull/3575
* [x] - Search Result should be 56dp tall
https://github.com/mozilla-mobile/android-components/pull/3575
* [x] - Search Result Icon and Label should align with Search field Icon and Label
https://github.com/mozilla-mobile/android-components/pull/3575
* [ ] - Search Result URLs should be Blue
* [ ] - Should transition from Main Toolbar at bottom to full Search UI at the top
* [x] - Search Result Favicons should be the favicon not a placeholder
* [x] - Search Shortcuts should be 56dp tall
https://github.com/mozilla-mobile/android-components/pull/3575
* [x] - Search Shortcuts should have sign spacing and alignments as Search Results
https://github.com/mozilla-mobile/android-components/pull/3575

[Reporter: AmyYLee] [Date: 05/01/19]

* [x] - Threhold for snapping back into position is too generous when scrolling on homescreen
https://github.com/mozilla-mobile/fenix/issues/2357

[Reporter: AmyYLee] [Date: 05/08/19]

* [x] - Left align search suggestions text and icon to search bar text and icon
![](https://user-images.githubusercontent.com/5992746/57488535-5beb3680-7281-11e9-9ec9-7328868574a0.png)
#3773

[Reporter: AmyYLee] [Date: 05/09/19]

**Comment by topotropic** [comment]
@AmyYLee there's an issue in landscape mode that you can hardly see a search result, is this addressed here? Thanks!

**Comment by AmyYLee** [comment]
@topotropic No I haven't checked this against landscape yet. This is a list that everyone can add to if they see an UX issue that affects quality but not accessibility or hinders functionality. If you think the issue affects accessibility then I would file it as a separate bug.

**Comment by sblatz** [comment]
@AmyYLee can I ask why we want this one?

>  - Search Results background is white should be "Foundation" color
If we do this, the search text field will just be an outline, and I think it would look a bit off...

**Comment by sblatz** [comment]
See [this comment](https://github.com/mozilla-mobile/fenix/issues/1184#issuecomment-506018203) for more info on making the engine icons look different.

**Comment by sblatz** [comment]
@AmyYLee I have updated the search box with lots of improvements. Please confirm that the boxes I've checked off are looking as expected 😄

**Comment by AmyYLee** [comment]
> @AmyYLee I have updated the search box with lots of improvements. Please confirm that the boxes I've checked off are looking as expected 😄

@sblatz These look good to me. Thanks!

**Comment by sblatz** [comment]
@AmyYLee Some more questions for you...

> - Search Result URLs should be Blue

Is this a must? This isn't the easiest to implement and doesn't match how the rest of our links show up as grey.

> - Should transition from Main Toolbar at bottom to full Search UI at the top

Do we have a video animation somewhere for this?

**Comment by sblatz** [comment]
@liuche @vesta0 can we move this one out of the sprint? I think we've addressed the most critical concerns.

**Comment by liuche** [comment]
works for me - it means we don't actually track this work but this is kind of a special case. I'm glad there's a checklist though!

**Comment by topotropic** [comment]
@AmyYLee can this be closed? Thanks!
