### ISSUE TITLE
[Product Quality] Settings - Checklist (Ongoing)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2273]
**Feature Level Checklist for Settings**

This is an ongoing list for product quality related bugs for this feature/component. Any non-essential UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Please see examples of what is considered essential and non-essential UX bugs [here]<---TBD. Essential UX bugs should be filed separately and triaged by product. Items that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed)

- - -
Current
![](https://user-images.githubusercontent.com/5992746/57163174-6bb8d580-6dbe-11e9-8bda-aaa69a4477ea.png)

Mock
![](https://user-images.githubusercontent.com/5992746/57165016-e9cbab00-6dc3-11e9-807a-781c1c941f88.png)

* [x] **Site Permissions:** Should be flushed to bottom of screen (not top)
* [x] **Site Permissions:** Margins and padding are not consistent
* [x] **Site Permissions:** "Remember…" checkbox is not aligned with permission request text
* [x] **Site Permissions:** Permission request text can run off the screen and get clipped instead of wrapping
* [x] **Site Permissions:** Button text should be sentence case instead of all-caps
* [x] **Site Permissions:** Primary action button should use "Accent" color
* [x] **Site Permissions:** Prompt does not have a scrim between prompt and web page
* [ ] **Settings:** Should have transition animation between settings screens
Should transition between categories - Please reference native android transitions for settings
https://cl.ly/10e2f112f0ee
Material Design reference page: https://material.io/design/navigation/navigation-transitions.html#peer-transitions
https://github.com/mozilla-mobile/fenix/issues/2136
[Reporter: AmyYLee] [Date: 05/03/19]

**Settings home:** 
https://mozilla.invisionapp.com/share/9SS40BM8H6Y#/350752852_Settings 

* [x] Remove dividers
* [x] Rename "Advanced" to "Privacy"
* [x] Remove indentation of "Set as default browser"
* [x] Remove icon and indentation of "Remote debugging via USB"
* [x] Remove icon and indentation of "Privacy policy"
* [x] Rename "Data choices" to "Data collection" in Settings

**Theme page:**

* [ ] Reduce height of list elements to 56 dp

**Misc:**

* [x] Reduce space between icon and label to 12dp (also on Theme, Tracking protection and Site permissions page)

[Reporter: Nicole]

**Comment by Amejia481** [comment]
[Site permission prompts have been updated](https://github.com/mozilla-mobile/fenix/pull/2304), many of these issues may be already fixed, worthwhile to take a look at the updated version to verify

![Screenshot_20190507-160113](https://user-images.githubusercontent.com/773158/57329303-80a8a800-70e1-11e9-9cac-7ffa9a62502b.png)

**Comment by Scripterr** [comment]
Hello @AmyYLee I would like to know is this issue still relevant, cause I would like to get transition animation between settings screens because going through setting screens makes pages to jump and looks unpolished for a product at this stage.
If it's still relevant can it be prioritised.

**Comment by AmyYLee** [comment]
> Hello @AmyYLee I would like to know is this issue still relevant, cause I would like to get transition animation between settings screens because going through setting screens makes pages to jump and looks unpolished for a product at this stage.
> If it's still relevant can it be prioritised.

@Scripterr Hi, yes this is still relevant. I've updated the bug with new transition specifications. Let me know if you have any questions. Thanks!

Settings: Should have transition animation between settings screens
Should transition between categories - Please reference native android transitions for settings
https://cl.ly/10e2f112f0ee
Material Design reference page: https://material.io/design/navigation/navigation-transitions.html#peer-transitions
