### ISSUE TITLE
FNX-5560 ⁃ [Product Quality] Library - Checklist (Ongoing)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2275]
**Feature Level Checklist for Library**

This is an ongoing list for product quality related bugs for this feature/component. Any non-essential UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Please see examples of what is considered essential and non-essential UX bugs [here]<---TBD. Essential UX bugs should be filed separately and triaged by product. Items that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed)

- - -
* [x] **Bookmarks:** Bookmark list items Icon is different size than Library categories
https://github.com/mozilla-mobile/fenix/issues/2130
* [x] **Bookmarks:** Bookmark items don't have favicons
https://github.com/mozilla-mobile/fenix/issues/2132
* [x] **Bookmarks:** In Edit Mode: Delete icon is black instead of white (there is no longer a delete icon)
* [x] **Bookmarks:** In Edit Mode: Name and URL text collide with the Clear icon (this is no longer an issue according to Nicole)
* [x] **History:** "Delete History" button is missing the button container
https://github.com/mozilla-mobile/fenix/issues/2133
* [x] **Library:** - Should transition between categories
https://github.com/mozilla-mobile/fenix/issues/2136

[Reporter: AmyYLee] [Date: 05/03/19]

**Comment by sblatz** [comment]
We are holding off on this work for now as library is potentially being redesigned.

**Comment by lime124** [comment]
removing ux label, we'll come back to this when we take  a look at library

**Comment by liuche** [comment]
@vesta0 and @topotropic to go over this list and see what we should do/skip.
