### ISSUE TITLE
[Meta] Create library of reusable Compose components

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#24339]
With all of the Compose refactoring, we should create a library of Composables so certain UI elements don't get written and re-written multiple times.

[Designs](https://www.figma.com/file/ujdiReypSypu2GhRgzArea/Android-Components?node-id=0%3A1)

1. [x] https://github.com/mozilla-mobile/fenix/issues/24337
2. [x] https://github.com/mozilla-mobile/fenix/issues/24338
3. [x] https://github.com/mozilla-mobile/fenix/issues/24391
4. [x] https://github.com/mozilla-mobile/fenix/issues/24524
5. [ ] https://github.com/mozilla-mobile/fenix/issues/24525
6. [x] https://github.com/mozilla-mobile/fenix/issues/24873
7. [x] https://github.com/mozilla-mobile/fenix/issues/24936
8. [x] https://github.com/mozilla-mobile/fenix/issues/25015
9. [x] https://github.com/mozilla-mobile/fenix/issues/25119
10. [x] https://github.com/mozilla-mobile/fenix/issues/25135
11. [x] https://github.com/mozilla-mobile/fenix/issues/25291 
12. [ ] Issue to make FAB composable 
13. [ ] Issue to add disabled state to all of our Button composables (waiting for #25119, #25291, and the yet-to-be-written FAB issue)
14. [x] https://github.com/mozilla-mobile/fenix/issues/23221
15. [x] https://github.com/mozilla-mobile/fenix/issues/25379
16. [x] https://github.com/mozilla-mobile/fenix/issues/25490
17. [x] https://github.com/mozilla-mobile/fenix/issues/27401
18. [x] https://github.com/mozilla-mobile/fenix/issues/28419
19. [ ] Issue to make switches
20. [ ] Issue to make check boxes
21. [ ] Add a disabled state to radio buttons
22. [ ] Add a disabled state to switches
23. [ ] Add a disabled state to check boxes
24. [ ] Issue to make form inputs
25. [x] https://github.com/mozilla-mobile/fenix/issues/27459
26. [ ] Issue to make menus
27. [x] https://github.com/mozilla-mobile/fenix/issues/28201
28. [x] https://github.com/mozilla-mobile/fenix/issues/27854
29. [ ] Fix broken previews in `MediaImage`
30. [ ] Re-examine the `maxLines` parameter of `Button`. Check with UX if we should still restrict buttons to one line of text.

_(file individual tickets and link them here)_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19896)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814199

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
