### ISSUE TITLE
Refactor Tabs Tray's interactors

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#25722]
Per https://github.com/mozilla-mobile/fenix/pull/25636#discussion_r903805714 and https://github.com/mozilla-mobile/fenix/pull/25636#discussion_r903843844, the Tabs Tray's interactors should be consolidated into one top-level interactor so there is a clearer call stack for handling user interactions. This way there is one entry point for everything Tabs Tray-related functionality and only one dependency passed down into front-end code consumers.

This effort should be split into the following issues:

**Phase 1 (minor refactoring noise and quick wins**
- [x] https://github.com/mozilla-mobile/fenix/issues/28261
- [x] https://github.com/mozilla-mobile/fenix/issues/28262
- [x] https://github.com/mozilla-mobile/fenix/issues/28263
- [x] https://github.com/mozilla-mobile/fenix/issues/28264
- [x] https://github.com/mozilla-mobile/fenix/issues/28516

**Phase 2 (substantive refactors)**

- [ ] https://github.com/mozilla-mobile/fenix/issues/28265
- [x] https://github.com/mozilla-mobile/fenix/issues/28266
- [x] https://github.com/mozilla-mobile/fenix/issues/28267
- [x] https://github.com/mozilla-mobile/fenix/issues/28268
- [x] https://github.com/mozilla-mobile/fenix/issues/26017

**Phase 3 (follow-up)
- [ ] Create an interactor/controller for the FAB
- [ ] Refactor the sync tabs portion of the tabs tray FAB to live in the FAB interactor/controller flow
- [ ] Decouple `TabsTrayInteractor` from `TabsTray.Delegate` after #21318 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20781)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814225

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
