### ISSUE TITLE
[meta] Refactor the Wallpaper feature to prep for A-C migration

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26034]
This issue is intended as a top-level issue tracking work to refactor the Wallpaper feature to host its state in the `AppStore` and initiate the actions it undertakes through the `Middleware` pattern, as well as abstract Fenix-specific implementations out. This has several benefits:

- architectural consistency
- allows clients to focus on state and interactions instead of implementation details
- creates an abstraction barrier

There are several subissues that will need to be completed for this to be considered done:

- [x] https://github.com/mozilla-mobile/fenix/issues/25985
- [x] https://github.com/mozilla-mobile/fenix/issues/26029
- [x] https://github.com/mozilla-mobile/fenix/issues/26052
- [ ] https://github.com/mozilla-mobile/fenix/issues/26030
- [ ] https://github.com/mozilla-mobile/fenix/issues/26033
- [x] https://github.com/mozilla-mobile/fenix/issues/26245

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21015)

**Comment by MozillaNoah** [comment]
You could optionally format this issue like the [meta] issues [here](https://github.com/mozilla-mobile/fenix/issues/24339) and [here](https://github.com/mozilla-mobile/fenix/issues/21318).

**Comment by MatthewTighe** [comment]
> You could optionally format this issue like the [meta] issues [here](https://github.com/mozilla-mobile/fenix/issues/24339) and [here](https://github.com/mozilla-mobile/fenix/issues/21318). That way each individual issue has a built-in status indicator without having to click into them.

Brilliant, thanks for pointing it out! I'll reformat this one if I've got time and definitely remember this for the future

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809805

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
