### ISSUE TITLE
Wallpapers - Download light/dark card colors

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#27095]
**Dependency**
- https://github.com/mozilla-mobile/fenix/issues/27094

**Todo**
- [x] Replace the existing `Wallpaper.cardColor` with `Wallpaper.cardColorLight` and `Wallpaper.cardColorDark`
- [x] Update `JSONArray.toWallpaperList()` to pull down `card-color-light` and `card-color-dark`
- [x] Add/update test(s) to `WallpaperMetadataFetcherTest`

**Notes for QA**
- This is more of a technical/coding story. The validation for this would be to ensure none of the existing wallpaper functionality is broken (Wallpaper selection, wallpaper onboarding, wallpaper downlading, etc.).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21625)
