### ISSUE TITLE
FNX3-16552 ⁃ [Breakdown Eng] History

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#275]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/221

**Comment by boek** [comment]
- [ ]  Add a history section to the library #355 
- [ ] Create the history management UI #357
- [ ] Allow the user to remove some, or all of their history #356
- [ ] Allow the user to search their history using the AwesomeBar #358
