### ISSUE TITLE
[Breakdown Eng] Private Browsing

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#277]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/216

**Comment by sblatz** [comment]
## Breakout Tickets
- [ ] #345: Add private browsing theme & assets
- [ ] #346: Home view for private browsing
- [ ] #347: Integrate a-c for private browsing
