### ISSUE TITLE
[Breakdown Eng] Share

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#279]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/92

**Comment by sblatz** [comment]
## Breakout tickets

- [ ] #329: Add android share sheet
- [ ] #330: Add long-press share
- [ ] #331: Send tab to other device
