### ISSUE TITLE
[Breakdown Eng] Download

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#280]
Breakdown: https://github.com/mozilla-mobile/fenix/issues/214

**Comment by boek** [comment]
- [ ] Add Downloads section to the Library (#348)
- [ ] Downloads UI (#349)
- [ ] Populate the downloads UI with a list of files that have been downloaded (#350)
- [ ] Give the user the ability to delete a download #352
