### ISSUE TITLE
[Product Quality] Collections - Checklist (Ongoing)

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2896]
**Feature Level Checklist for Collections**

This is an ongoing list for product quality related bugs for this feature/component. Any non-essential UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Essential UX bugs should be filed separately and triaged by product. Items that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed)

- - -
* [ ] Need a gradient background on top and bottom to remove hard edge when scrolling through tabs

Current:
![](https://user-images.githubusercontent.com/5992746/58433725-7c3f3180-8086-11e9-910c-d5fbe6a6987a.png)

Specification:
![Screen Shot 2019-05-29 at 1 26 09 PM](https://user-images.githubusercontent.com/5992746/58577865-6f9d1380-8215-11e9-97b8-829caefeccb3.png)

* [x] Selecting tab to save to collection changes opacity (flickers) on tap. The tab should be @100% opacity at all times.
See video for reference: https://cl.ly/b2e436567b99
* [x] Tap overlay should be default grey (currently it's a purple tint) 
See video for reference: https://cl.ly/b2e436567b99
* [x] Checkbox on tab should be #592ACB (should be the same bright purple as action bar below)

![](https://user-images.githubusercontent.com/5992746/58433390-1a31fc80-8085-11e9-9ad3-48d3ce226045.png)

* [x] Collections icon is too big (should be 24x24 px with icon padding)
![](https://user-images.githubusercontent.com/5992746/58433922-30d95300-8087-11e9-8c5f-63976a90446c.png)

* [x] "Save to collections" text is too bold
![](https://user-images.githubusercontent.com/5992746/58433950-4c445e00-8087-11e9-825f-e86e5356c52b.png)
* [x] Confirmation snackbar on homescreen after saving a collection should be Accent Dark (#312A65)
![](https://user-images.githubusercontent.com/5992746/58434703-fd002c80-808a-11e9-97f5-86d3753f671a.png)
* [x] Check the height of the open tab card (currently it looks too short so the text is very tight to the edge of the card when there's 2 lines). See screenshot and spec below

![](https://user-images.githubusercontent.com/5992746/58582306-703aa780-821f-11e9-93dc-d8e1ad3aece5.png)

* [x] Spacing is too wide between Save to collection button and open tab - Should be equal distance (like open tabs spacing)
![](https://user-images.githubusercontent.com/5992746/58582533-e4754b00-821f-11e9-8d5b-0272a71079d6.png)

[Reporter: Amy Lee, Date May 27 2019]

* [ ] When in add to collection modal, if the list of opened tabs overflows past the viewport, the tabs list should be positioned flushed to the top of the header and overflow at the bottom as a default starting point. If the list of open tabs doesn't exceed past the viewport, then it should sit above the action bar. 

[Reporter: Amy Lee, Date June 6 2019]

**Comment by AmyYLee** [comment]
@sblatz @ekager

**Comment by vesta0** [comment]
@AmyYLee you mentioned that Product quality checklists aren't UX P1 blockers right?

**Comment by AmyYLee** [comment]
> @AmyYLee you mentioned that Product quality checklists aren't UX P1 blockers right?

These aren't blockers but I would say if the list is marked as P1 that we want to really try to get these issues fixed or the overall product quality suffers, especially if the list is extensive.

**Comment by sblatz** [comment]
@AmyYLee can you help clarify what you mean by:

>  Need a gradient background on top and bottom to remove hard edge when scrolling through tabs

**Comment by sblatz** [comment]
@AmyYLee When modifying the "open tab card" to have the right dimensions according to the mocks, the favicons look overly large. Is this expected?

They're now 66x66 (matching the mocks) with 8dp margins and the cards are 82dp tall.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/60623000-81cf1c00-9d96-11e9-8cfa-8ff9e8f7909b.png">

**Comment by AmyYLee** [comment]
> @AmyYLee When modifying the "open tab card" to have the right dimensions according to the mocks, the favicons look overly large. Is this expected?
> 
> They're now 66x66 (matching the mocks) with 8dp margins and the cards are 82dp tall.
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/60623000-81cf1c00-9d96-11e9-8cfa-8ff9e8f7909b.png">

@sblatz Let's leave this one for now since this layout will most likely change.

**Comment by AmyYLee** [comment]
> @AmyYLee can you help clarify what you mean by:
> 
> > Need a gradient background on top and bottom to remove hard edge when scrolling through tabs

I'm referring to adding a shadow to soften the edges on the top and bottom like this. Does that make sense? 
<img width="536" alt="Screen Shot 2019-07-03 at 5 22 01 PM" src="https://user-images.githubusercontent.com/5992746/60625897-28c3b000-9db7-11e9-9eee-a6be9093d673.png">
<img width="397" alt="Screen Shot 2019-07-03 at 5 21 48 PM" src="https://user-images.githubusercontent.com/5992746/60625898-28c3b000-9db7-11e9-9d22-f1e7c7db48de.png">

**Comment by sblatz** [comment]
Touched base with @topotropic and it sounds like we want to hold off on these polishes until we've settled on a final collections design.

@bifleming can we move this off the board? I'll throw a blocked label on it.

**Comment by liuche** [comment]
@vesta0 and @topotropic to go over this list and see what we is ready for eng to do.

**Comment by vesta0** [comment]
Waiting until after user testing the new tab tray.

**Comment by liuche** [comment]
@vesta0 were there any insights from the UR from 8/21 that affect this bug?

If not, @lime124 can we remove this from the board, since it looks like this isn't particularly actionable right now, and should be represented by other bugs? (or even close it)

**Comment by topotropic** [comment]
So all that is left here is the gradient at the bottom and the drop shadow in selection mode – when we keep Collections as is. We had a delay running the test and will discuss early next week the results again.

**Comment by liuche** [comment]
Just doing the last checkbox in comment 0, there's a screenshot.
