### ISSUE TITLE
[Meta] Web Share

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#328]
Related meta: #5783

### Description
>Web Share provides a way to trigger the native share dialog of a device when sharing content — say a link or a contact card — directly from a website or web application.

### Resources
* https://w3c.github.io/web-share/level-2/
* https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* https://css-tricks.com/how-to-use-the-web-share-api/

### User stories
* [x] #780 - Share from my installed PWA to other installed (native) apps

### Tasks
* [x] mozilla-mobile/android-components#3486 - Add support for Web Share API

### Dependencies
* [x] [Bug 1312422](https://bugzilla.mozilla.org/show_bug.cgi?id=1312422) - DOM implementation of Web Share API
* [x] [Bug 1402369](https://bugzilla.mozilla.org/show_bug.cgi?id=1402369) - GeckoView: Implement Web Share API

**Comment by NotWoods** [comment]
All issues have been completed so I'll close this meta.
