### ISSUE TITLE
[Meta] Sync Form Address data

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#339]
### User Story
As a user, I want to sync my form address data across my Fx connected devices, so I can re-use it to auto-fill new forms and complete my task faster.

### Acceptance Criteria
* [ ] (p1) I can choose to sync form address data
* [ ] (p1) When sync form address data is selected, my browser will auto-fill my address on a new form using synced form data
* [ ] (p1) I know how often user chooses to sync form address data (Telemetry Ticket TBD)
* [ ] (p2) When sync form address data is selected, I can see my synced form address data from other Fx connected devices in my Fenix settings

**Comment by liuche** [comment]
@linacambridge we're sizing this based on the assumptions that:
- Address Storage layer is part of AS Q4 goals
- AS will be doing the AC work? (I would like confirmation on this)

**Comment by madb1lly** [comment]
Hi all,

I was expecting to be able to use this today but was surprised it doesn't exist yet, but then neither does autofill of forms either. I definitely want to be able to do this with Fenix, I'd like to return to my old ability to quickly fill out forms when mobile using form data saved on desktop.

Cheers 🙂

**Comment by madb1lly** [comment]
Hi all, isn't there a secret setting to enable this? So, it's in the works and bug can stay open until it's in the release version.
Cheers 🙂

**Comment by mduchev** [comment]
Still waiting for this one.

**Comment by madb1lly** [comment]
Hi @gabrielluong,
I see you've raised a few issues for address form data. This Meta has been auto-closed, but should it be reopened as a catchall for this topic? Or is there another meta to follow now?
Cheers :)
