### ISSUE TITLE
[Meta] Bookmarks discoverability and navigation

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3894]
### Why/User Benefit/User Problem
-As a user I want to be able to easily discover how to bookmark a page (related to #3927, #3104, #3853) 
-As a user I want to be able to quickly access my saved bookmarks in fewer steps (based on user feedback, related #1487, #3677)
-As a user I want to easily understand when to create collections vs add a bookmark, so I can have a more intuitive user experience (based on user feedback)

### Acceptance Criteria
- [x] I know how to bookmark a page (addressed in #1487)
- [x] I can access my saved bookmarks quickly (addressed in #1487)
- [ ] I understand the distinction between bookmarks and collections.

### Reference
Based on recent user feedback
-Bookmarking a site is somewhat hidden and users can't find it. 
-Some users thought we had replaced bookmarks with collections (and didn't have bookmarks) and wondered why collections didn't sync with desktop bookmarks.
-Navigating to saved bookmarks take too many steps.

Also see #3100

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by liuche** [comment]
Also part of Homescreen rewrite as part of #3860 - is being put on hold, though the research is done, and maybe there are some quick wins.

**Comment by liuche** [comment]
@topotropic will break this down and then those can be worked on.

**Comment by topotropic** [comment]
We can break the meta down into the user stories as described in the root issue.

I'll start looking into the one with the fewest dependencies which is "As a user I want to be able to quickly access my saved bookmarks in fewer steps" and spec out a design for end of sprint (Aug 30). 

The other two stories require some more coordination and research and won't be ready for end of sprint:
- As a user I want to be able to easily discover how to bookmark a page (related to #3927) --> I'll discuss this with Adam and see what his ideas are for QAB
- As a user I want to easily understand when to create collections vs add a bookmark, so I can have a more intuitive user experience (based on user feedback) --> I'll discuss this with Stephen

**Comment by vesta0** [comment]
Sounds like a plan @topotropic

**Comment by topotropic** [comment]
Ok, I updated https://github.com/mozilla-mobile/fenix/issues/1487 to reduce taps it takes to access bookmarks from home screen;  this could be pulled into the next sprint @lime124 @vesta0 @liuche

**Comment by vesta0** [comment]
Yes we can look at the 2 remaining items that are related to user education in Q4.

- I know how to bookmark a page.
- I understand the distinction between bookmarks and collections.

**Comment by lime124** [comment]
the removal of QAB #5588 and the toolbar menu #4281 tickets should cover the first bullet point 

#5652 is filed to cover the last bit of work. closing!
