### ISSUE TITLE
[Meta] Tracking Protection

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4246]
The purpose of this meta is to track all the relevant docs and issues for Enhanced Tracking Protection. Once all the issues are closed, the meta can be closed. 

[Feature Brief](https://docs.google.com/document/d/1h0fGejj1uMmg7jYBS3hUcp0FuRehGDMhw2xEfuB7aZU/edit#)

[A-C board](https://github.com/orgs/mozilla-mobile/projects/33)

[UX Mocks](https://mozilla.invisionapp.com/share/R8T6GDUDW3B)

Related issues:

- [x] Enhanced Tracking Protection #1749 
- [x] Social Tracking Protection #3571 
- [x] Tracking Protection Visibility #3901 
- [x] Improved Tracking #5281 
- [x] Integrate new exceptions management #5646

**Comment by lime124** [comment]
@bifleming @vesta0 @liuche - this is hanging out in the UX column but it's done. where should we move it to?

**Comment by liuche** [comment]
Okay - if this is done, then we should:
1) Close it
2) Move all the issues into the Feature Backlog and label them "ready for eng"

I'll do that for this bug!

**Comment by liuche** [comment]
No QA needed, because this is a Meta, and the work has yet to be done.

**Comment by jonichan** [comment]
@vesta0 We have an draft here for your review: https://docs.google.com/document/d/1IfDoaW8T_vKKO3RkGAJG76amU8eEUH0p5ngdFwS_88I/edit?usp=sharing. Please let me know if you think it's ready to go.

**Comment by liuche** [comment]
Metas will follow the last bug through the sprint board.

**Comment by liuche** [comment]
Dropping an update in here about the status of tracking protection, from talking to ekager:

**Nightly/Debug flag**: All panel and toolbar UI is behind this flag, as well as the ability to choose between strict/standard
**In Production**: the new lists aligned with desktop as "strict" mode; slightly new Settings UI with the "learn more" graphic
**In Progress**: Before shipping the panel/toolbar UI, want to use the new exceptions list (AC PR draft opened by @Arturo) and a more accurate list of "trackers blocked by category" is being exposed through GV/AC as well: https://github.com/orgs/mozilla-mobile/projects/33

**Comment by vesta0** [comment]
All the work under this meta has been completed. Thank you so much @ekager @Amejia481 @AmyYLee 👍
