### ISSUE TITLE
Iterate on Tab Management & Collections

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#4285]
## User Story
After the MVP, we should take a look at the feedback coming and see what we need to iterate on. Collecting several homescreen related issues here for UX to consider and tackle at the same time.

Possible design solution - https://mozilla.invisionapp.com/share/QSRWREJMV9D#/372970523_Latest

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
- I can do …  (e.g. add a bookmark)

### Reference Issues

- [ ] Differentiate between Bookmarks and Collections #3894 

- [x] Animation: Closing a tab #1288 

- [x] Floating action button: https://github.com/mozilla-mobile/fenix/issues/739

- [x] Move 3 dot menu to bottom: https://github.com/mozilla-mobile/fenix/issues/561

- [ ] Design for Switch to Tab #1500 

See if animation proposals still apply: https://github.com/mozilla-mobile/fenix/issues/3004
UI to name/rename collections: https://github.com/mozilla-mobile/fenix/issues/3831
save to collection button: https://github.com/mozilla-mobile/fenix/issues/3752
long press - https://github.com/mozilla-mobile/fenix/issues/2696
move new tab button to bottom: https://github.com/mozilla-mobile/fenix/issues/1935
https://github.com/mozilla-mobile/fenix/issues/1063
close tabs automatically #3760

**Comment by lime124** [comment]
@vesta0 @topotropic

**Comment by apbitner** [comment]
May be some overlap with https://github.com/mozilla-mobile/fenix/issues/3894

**Comment by liuche** [comment]
Now that the user testing is done, next steps are: get actionable items, so that we can prioritize and add to sprints.

**Comment by vesta0** [comment]
@lime124 and @topotropic please file actionable issues that came out of this user testing, and close this issue.

**Comment by topotropic** [comment]
I'll close this issue, we can track the work via https://github.com/mozilla-mobile/fenix/labels/Feature%3ACollections and https://github.com/mozilla-mobile/fenix/labels/Feature%3AHomeScreen. I'll also file new issues based on UR.
