### ISSUE TITLE
[Meta] Media

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4306]
This meta will contain all the features and assets related to the media support enhancements in Fenix.

Gecko media team meta, tracking Media isssues: https://bugzilla.mozilla.org/show_bug.cgi?id=1609200

[Feature Brief](https://docs.google.com/document/d/1hybjPmRD4uHBV9jmhLjhukqctaPxnlJJXGEYTejVegs/edit#)

A-C board: https://github.com/orgs/mozilla-mobile/projects/26

UX: https://share.goabstract.com/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design

Known requirements:
- [x] Toggle Media Autoplay #255 
- [x] Media control notification #2551 
- [x] Continue media playback while Fenix is in background #1113 
- [x] Show which tab is playing audio #1114 
- [x] User choice for different media defaults in private browsing when relevant (e.g. Pause media playback in Private Browsing when minimizing the app #1117)
- [x] Integrate a/c work #4431 
- [x] [Bug] Private browsing history leaked to system through media playback notifications #4759

**Comment by vesta0** [comment]
@topotropic I have updated the meta and added a link to the Feature Brief, AC board, and related issues.

**Comment by topotropic** [comment]
@lime124 size M

**Comment by liuche** [comment]
This UX work is done, removing from board.

**Comment by sblatz** [comment]
I'm confused--why are we tracking a meta here in the sprint "in progress" column? 🤔 

I thought only individual stories went through here @liuche

**Comment by vesta0** [comment]
This work is completed, bugs such as #5636 will be addressed separately.
