### ISSUE TITLE
[Meta] Improvements for code and build health

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4326]
A list of random tasks, tools and other things we do/use in AC that we may want to do/use in Fenix too. Applying some of those things may require filling separate issues.

- [x] Update detekt to latest version to use latest checks (`1.0.0.RC9.2` -> `1.0.0-RC16`)
- [x] Update ktlint to latest version to use latest checks (`0.31.0`-> `0.34.2`)
* [x] #4508: Enable "warnings as errors" and fix all existing warnings
* [x] #4507: Enable codecov coverage reports for master and other branches (+ PR comments). This makes it easier to uncover untested parts of the code base and helps seeing the test coverage of new patches.
- [ ] Enable "Require branches to be up to date before merging". This requires branches to be rebased before they can be merged (either manually or via "Update Branch" button in PR UI). We have this enabled for AC. This can be annoying at times if you need to update the PR a couple of times (We are thinking about bot support for that in AC). But it avoids surprises when merged PRs start failing on master. With that enabled a green PR means a green master.
- [ ] Stable-ize dependencies. We are using a lot of AndroidX alpha and beta versions. This is a bit scary since those versions are less tested / proven. It's also scary that this overrides what AC uses at runtime in Fenix and AC is on stable AndroidX versions. Especially if there are major version differences this can lead to unexpected bugs.

**Comment by liuche** [comment]
@sblatz will break this out, and put E3 into the sprint.

**Comment by sblatz** [comment]
> Enable "Require branches to be up to date before merging". This requires branches to be rebased before they can be merged (either manually or via "Update Branch" button in PR UI). We have this enabled for AC. This can be annoying at times if you need to update the PR a couple of times (We are thinking about bot support for that in AC). But it avoids surprises when merged PRs start failing on master. With that enabled a green PR means a green master.

I'm not sure how to feel about this one. I'm worried that PR's will rot even more if we enable this setting. I've definitely felt very slowed down by this on AC and I think we've rarely (if ever) had an issue come from this on our repo.

**Comment by sblatz** [comment]
De-prioritizing to p3 as I don't think the rest of these are super critical. Codecov was the big win here :)
