### ISSUE TITLE
[Meta] Turn on Bottom Dynamic Nav Bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4383]
We chose to disable the dynamic nav bar and make it fixed for MVP due to issues we were investigating in GeckoView. We should look into enabling this before the next major release since this was always the plan AND it's a highly requested user feature.  

Dynamic top nav bar is #5694 and already done.

### User Story
As a user browsing in Fenix, I want the nav bar to auto-hide when I scroll down, so I can view web content in full screen. 

#### Dependencies
- [ ] GV bug: Bad behavior on some sites https://bugzilla.mozilla.org/show_bug.cgi?id=1594451
- [ ] AC bug: Implementing new GV APIs (setVerticalClipping, setDynamicToolbarMaxHeight): https://github.com/mozilla-mobile/android-components/issues/4780

#### Acceptance Criteria
- [ ] When I scroll down a webpage in Fenix, the nav bar auto-hides.
- [ ] When I scroll back up, the nav bar appears. 
- [ ] This should be behind a Nightly flag, and track when the GV feature is mature (and bugs that come out of this have been fixed).

**Comment by Madis0** [comment]
Relevant idea with potentially better user security: #3805

**Comment by liuche** [comment]
According to GV, we can now turn on the AC dynamic nav bar, which is in GV Nightly, so we start seeing what the bugs are.
This should be behind a Nightly flag, because we don't want this to be on Release until the GV bugs surface and are fixed.

**Comment by KasperNymand** [comment]
Would it be possible to make this optional?

**Comment by bifleming** [comment]
@vesta0 we removed this from our Q4 release, but I think this is the one that we want in Q4 -- it sounds like it's just turning on the dynamic nav bar so we can see which bugs need to be fixed.

**Comment by cpeterso** [comment]
The GV team has a couple minor GV issues to be fixed for the dynamic toolbar, but feels the dynamic toolbar is ready to re-enabled for Fenix Nightly (only) user testing. The dynamic toolbar shouldn't ride the Fenix trains yet.

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/pull/6571 will give us dynamic toolbar on top, but not for bottom

**Comment by liuche** [comment]
I'm going to update this to only include Dynamic Bottom Bar, bc #5694 is already finished.

**Comment by liuche** [comment]
I don't see any more dependencies here, so this is probably ready to work on?

**Comment by liuche** [comment]
Still have some bad behavior on sites like The Guardian https://bugzilla.mozilla.org/show_bug.cgi?id=1594451

**Comment by vesta0** [comment]
Let's turn this on in Nightly and test it.

**Comment by hiikezoe** [comment]
Note that when the toolbar is toggled visible/hidden on fullscreen stuff, we also need to call engineView.setDynamicToolbarMaxHeight(0) or engineView.setDynamicToolbarMaxHeight(`toolbar height`) respectively.  Probably here https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L379-L390

**Comment by softvision-miralobontiu** [comment]
Verified that:
- when scrolled down a webpage in Fenix, the navbar auto-hides,
- when scrolled back up, the navbar reappears, both in normal and private mode.
Tested with Google Pixel (Android 10), and HTC 10 (Android 8) on the latest Nightly build from 2/26.

**Comment by sblatz** [comment]
Since this is only enabled in nightly/debug, i'm going to file a "remove feature flag" issue :)

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/issues/8775

**Comment by bogas04** [comment]
#8777
