### ISSUE TITLE
[Meta] Open In Private Browsing Mode

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#4390]
This Meta will contain all the features and assets related to Opening In Private Mode (Focus Parity)

[Feature Brief](https://docs.google.com/document/d/11udhneY8nCmE2Dy_57rRlWgbG2y4YbBlGYgHHnw4l2o/edit?usp=sharing)

[Research for Focus for Fenix team](https://docs.google.com/presentation/d/1_k_lphwWbo9Zw_o9L7ngI5MLW6ovWXKsMENatxHBwnE/edit#slide=id.g25275a8168_0_425)

Known Requirements:

- [x] Launcher Icon for PBM: #419
- [x] ~~Allow user to always open 3rd party links in PBM + TP: #514~~
- [x] Persistent notification to close private browsing tabs #2053 
- [x] Delete All Private Tabs Redesign: #2834 

Open in Private Browsing Spec
https://mozilla.invisionapp.com/share/DUTCUDLZ4MC

Engineering effort breakdown:

**Engineering bugs here**
- [x] Transition to PB isn't made after sharing a page from normal to private browsing #5254 
- [x] Fenix Homescreen icon long-press feature not working properly #5296

**Comment by liuche** [comment]
Once any of these sub-bugs are ready for eng, please move them into the Prioritized Feature Backlog!

**Comment by lime124** [comment]
sized at a M per Amy.

**Comment by liuche** [comment]
Feasibility meeting (probably) 8/6 (after holiday) and hopefully then it can be ready to be worked on.

**Comment by vesta0** [comment]
@vrudesai please see Chenxia's note above re updating user stories and acceptance criteria based on the final designs!

**Comment by sblatz** [comment]
@mheubusch are you able to provide strings for:

* "clear private browsing" part as we discussed in our meeting: https://mozilla.invisionapp.com/share/DUTCUDLZ4MC
* tip in focus: https://github.com/mozilla-mobile/focus-android/issues/4329

**Comment by lime124** [comment]
everything is done but final copy which i think is ok for eng to take.

**Comment by AmyYLee** [comment]
@sblatz @lime124 Final copy is in the spec now. What is still outstanding is copy for the tip in focus here https://github.com/mozilla-mobile/focus-android/issues/4329

**Comment by mheubusch** [comment]
Updated the Focus bug so can we consider copy done for all?

**Comment by colintheshots** [comment]
Do we have all the strings we need here? Can I remove the strings:needed label?

**Comment by AmyYLee** [comment]
> Do we have all the strings we need here? Can I remove the strings:needed label?

Strings have been provided for this bug. Removing strings:needed label.

**Comment by liuche** [comment]
@jyeontaek will add newly filed issues to this meta. They will be fixed today so no need to count for this sprint.

**Comment by sblatz** [comment]
@vesta0 can this be closed? I believe this feature is done.

**Comment by vesta0** [comment]
This feature is done :)

**Comment by glawrence** [comment]
I am sorry to say but I was hoping it was not done! To be honest I thought this would give me the option to control how HTML links on the phone were opened. I can set the default app to Firefox Preview but it always opens in "normal tabs", I wanted to be able to get them to open in Firefox Preview Private Tabs. So, open a URL in another app and Firefox Preview opens it up in a Private Tab, which is what Firefox Focus does. Maybe I missed something, and I apologise if I did. Happy to open a new issue, if that's easier/better, assuming I am making sense!

**Comment by lime124** [comment]
@glawrence if i'm following what you're saying you should be able to do that now this has landed. there is a setting that when toggled on will open 3rd party links in private browsing mode. 

STR 
pre -req: 
fenix is default browser. 
"launch links in private tab" setting on

1. in gmail open an email, click on a link
2. observe - Fenix opens the link in a private tab

Please file a new issue if your experiences are different (e.g. a bug) or I've totally misunderstood what you were intending and we have additional uses cases to solve for. Thanks!

**Comment by sblatz** [comment]
@glawrence Yes, @lime124 is correct. That behavior should be in our nightly and in our upcoming release next week :)

**Comment by glawrence** [comment]
Thank you @sblatz that is fantastic news and I look forward to the release next week
