### ISSUE TITLE
[Meta] Find downloaded files in browser

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4417]
[Feature Brief](https://docs.google.com/document/d/1s9ISItNnM38NBk9ixOADOT4iZBUqKNtt6HC45sbEKa8/edit#)

### User Story
As a user, I want to be able to easily find and manage my downloads in Fenix, so I can have control over my downloaded files. 

### Dependencies
A-C project board [here](https://github.com/orgs/mozilla-mobile/projects/34)

### Acceptance Criteria

- [x] #1657 Integrate with GeckoView download manager
- [x] #5491 Spike for UX/eng to investigate MVP
- [x] #349 Find my downloaded files in the browser

**Comment by liuche** [comment]
Would be helpful for UX to work w/ @pocmo on figuring out what UX would be needed.

**Comment by liuche** [comment]
QA has said they'd like a little extra time to test this, so landing early in a sprint, or behind a feature flag.

**Comment by sblatz** [comment]
This ticket needs a spike from UX/eng to decide what the MVP is for this. Points to consider:
- We currently only get a notification from AC when the download is done, none of this data is persisted, we don't progress or error information. For more info [see this Slack convo](https://mozilla.slack.com/archives/CA4JKKLSG/p1569257054060700)

**Comment by liuche** [comment]
Filed spike here: #5491

**Comment by liuche** [comment]
I updated this issue to include #5582, which is the remaining work for Q4 on Downloads. The rest will require more UX work, but that's the MVP we'd like to ship (in Q4).

**Comment by vesta0** [comment]
@liuche this issue should not include #5582 since we changed it (based on direct feedback from the team) that this part was not doable for Q4 (you can see that I moved it to Q1) and only #5582  was doable in Q4.

**Comment by vesta0** [comment]
This is all Android Components work that the Fenix team may decide to pick up in Q1.

**Comment by vesta0** [comment]
A-C will need to provide an API for the Fenix team to build the UI.

**Comment by Bhooty** [comment]
Still can't see the downloads in app :(
But downloads seem to work now :3

**Comment by vesta0** [comment]
The user stories that we wanted to address with this meta have been implemented. Thank you!
