### ISSUE TITLE
[Product Quality] Main Browser Toolbar - Checklist (Ongoing)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4538]
Remaining items from #2203.

- [ ] **Toolbar:** Does not have a transition between page and start screen (tab switching)
Please reference https://github.com/mozilla-mobile/fenix/issues/1289 
[Reporter: AmyYLee] [Date: 05/01/19]

- [x] **Quick Action Bar:** Does not hide correctly while scrolling - QAB when expanded should go into collapsed version before it disappears complete with the search bar. 
[Quick Action Bar Spec](https://mozilla.invisionapp.com/share/K3RKVUJUG5B#/screens)
[Quick Action Bar - Reference.mp4.zip](https://github.com/mozilla-mobile/fenix/files/3135936/Quick.Action.Bar.-.Reference.mp4.zip)
[Reporter: AmyYLee] [Date: 05/01/19]
[Edit: Sawyer] [Date: 08/01/19]: I think we should **hold off** on this one for now since it will be fixed once we have a dynamic toolbar again and is very difficult to implement with the current solution.
[Edit: Tif oct 24, 19] QAB is being removed so this is no longer relevant.

- [x] **App Menu:** Left and Right margins should be 16dp
[Reporter: AmyYLee] [Date: 05/01/19]
[Edit: Sawyer][Date: 08/05/19]: This will require a lot of work, unfortunately. The fix is to make the browser menu work with `wrap_content`, but that is [pretty difficult](https://github.com/mozilla-mobile/android-components/issues/3703). We should get this prioritized in AC if we care about it.
This checkbox is related to #1871.

- [x] **Search:** Does not have a transition for searching / entering address from toolbar 
[Reporter: AmyYLee] [Date: 05/01/19]

**Comment by vesta0** [comment]
@AmyYLee and @sblatz please indicate whether the 3 remaining items on this list are still valid and important considering the recent re-designs.

**Comment by AmyYLee** [comment]
> @AmyYLee and @sblatz please indicate whether the 3 remaining items on this list are still valid and important considering the recent re-designs.

@vesta0 @sblatz 

**"App Menu: Left and Right margins should be 16dp"**
Still relevant 

**"Search: Does not have a transition for searching / entering address from toolbar"**
Now that the search bar on homescreen is at the bottom, I don't think we should have the search bar move upwards to the top since it makes it feel laggy. Can we copy the transition of the search bar when a user is on a website and they tap on the search bar? The transition has the keyboard sliding up and the search bar instantly appears at the top. 

**Toolbar: Does not have a transition between page and start screen (tab switching)**
Not relevant since Nicole is redesigning tap switching.

**Comment by vesta0** [comment]
Remaining items have been filed as separate bugs and tracked on the feature polish board:
https://github.com/mozilla-mobile/fenix/projects/27
