### ISSUE TITLE
early feedback for history section implementation

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#465]
In #355 a first implementation of the history section in the library landed. \o/ Here is some early feedback. Probably you already know some of the issues, that's why I won't create separate reports for each issue.

- [ ] (1) There should be no about:blank in history => #1318 
- [x] (2) The first item should be the newest history entry, at the moment the oldest entry is the first one. => #607
- [ ] (3) Duplicates should be filtered out. I guess if I visite site A and then site A again the history shows entries for both visits, because I have identical entries in my history. => #1331 
- [ ] (4) Redirects should be taken into account. If I enter "google.com" in the address bar the history shows "http://google.com", then "http://www.google.com" and then "https://www.google.com. There should be only one entry. => #1332 
- [ ]  (5) data: URI don't wrap and overlap the "column" with the "three dots" icon => #1330
- [ ]  (6) the favicon placeholder is not correctly aligned (should be moved a bit to bottom) => #1333 

### Device information

* Android device: HTC U11 w/ Android 8.0.0
* Fenix version: 1.0.1907

**Comment by Cheap-Skate** [comment]
I would add

font should match the Library font (at the moment I think it's larger and maybe bold).

The "back" "search" and "close" icons need to be reachable one-handed e.g. put them at the bottom. See also #468

**Comment by cadeyrn** [comment]
> The "back" "search" and "close" icons need to be reachable one-handed e.g. put them at the bottom

I disagree. I saw your other isues but I don't think _everything_ has to be at the bottom of the interface. Such bars belongs to the top, in my opinion.

**Comment by Cheap-Skate** [comment]
Ha ha I forgot about using the Android back button to get out of "Your Library". I'm an idiot :)

In general re one-handed use

It seems that users are getting very excited about Fenix's "toolbar at the bottom" because of one-handed use. The more they can do one-handed the more excited they might become. So it's probably worth thinking hard about what they can and can't do one-handed and trying some things out. Perhaps having a UI policy e.g.

"URL navigation is always one handed"
"search is always two handed"
etc

**Comment by cadeyrn** [comment]
I attached a screenshot where you can see the issues 4 (with bing.com and yahoo.com), 5 and 6. 

![screenshot_20190213-204633](https://user-images.githubusercontent.com/1100614/52739733-d46b8f80-2fd1-11e9-84ca-781bec1dadab.png)

**Comment by cadeyrn** [comment]
It looks like there was a fix for (5) because it's truncated now and shows "…" at the end. But it's truncated too late - there is no space between the "…" and the "three dots" button.

For (2) there is now a another issue. I linked to the ticket in comment 0.

Please let me know if I should open dedicated tickets for each or some of the issues described in comment 0.

**Comment by vesta0** [comment]
@cadeyrn thank you for finding and filing these bugs! 2 and 5 were fixed and there is a bug filed for 1 but please feel free to go ahead and create bugs for 3,4,6.

**Comment by cadeyrn** [comment]
@vesta0 okay! (5) is not yet fixed. I filed new issues for (3), (4), (5) and (6).

**Comment by vesta0** [comment]
Thanks!
