### ISSUE TITLE
[Meta] Create builds that technically could replace Fennec

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4873]
This is a new version of the closed meta issue #662 (only `MUST` tasks).

This issue only focuses on the technical requirements to create builds that can replace Fennec. Migrating data or implementing transition UI is not part of this issue. The primary goal of the work listed here is to make the transition from Fennec to Fenix technically feasible in the case where we decide to replace Fennec with Fenix (eventually).

### Build config

- [x] Create a build type for replacing Fennec. We have `fenix*` build types now. So it seems to be appropriate to create a `fennec*` one.
- [x] Reuse `sharedUserId` from Fennec (Nightly / Beta / Release)
- [x] Build on top of (or re-use) versionCode mechanism of Fennec
- [x] Reuse Fennec package names

### Releng

- [x] Reuse Fennec signing keys for `fennec` build.

### Tokens

Figure out which tokens to use. Do we use the "Fenix production" tokens, the "Fennec production" tokens or do we need completely new ones?

- [ ] Adjust: TBD - Sent mail to Chenxia and Loren.
- [ ] Leanplum: TBD - Sent mail to Chenxia and Loren.
- [x] Sentry: Created a separate project (`fenix-fennec`) and updated DSN in secret.
- [x] Firebase: Added Fennec production values to secret.
- [x] Codecov: Not needed. Ideally we do not upload any coverage reports for this build specifically.

**Comment by pocmo** [comment]
https://searchfox.org/mozilla-central/source/python/mozbuild/mozbuild/android_version_code.py

**Comment by creesch** [comment]
Does this also account for the migration of webextensions when they get implemented? #574

**Comment by pocmo** [comment]
build type (`fennecProduction`) and build config are in place now. Handing off to @mitchhentges for the RelEng work needed to get this built and signed in automation. :)

**Comment by mitchhentges** [comment]
I need to do two things here:
* Update `signingscript` config to allow Fenix to be signed with Fennec's key
* Update automation to produce a fennec-signed Fenix build

**Comment by mitchhentges** [comment]
@pocmo can you update [the secrets for `fennecProduction`](https://tools.taskcluster.net/secrets/project%2Fmobile%2Ffenix%2FfennecProduction) (or send them to me)? I'm not sure which ones you want to reuse from [regular `production`](https://tools.taskcluster.net/secrets/project%2Fmobile%2Ffenix%2Fproduction) and which should be recreated

**Comment by pocmo** [comment]
@mitchhentges That is a great question. I added the list of tokens to the list in the issue description. For some of them I need to figure this out first. For sentry I'll create a separate app project and update the token. In the meantime we can create the builds with dummy tokens and do not need to block on them.

**Comment by pocmo** [comment]
Updated the secret and added the right values for Firebase (Fennec production values) and Sentry (separate project). Waiting to hear back regarding Adjust / Leanplum (but as said above this doesn't need to block).

**Comment by pocmo** [comment]
Just installed the latest `fennecProduction` build over Firefox for Android (installed from Google Play). It works! ✨

**Comment by pocmo** [comment]
Continue with the two tokens in this new issue:
https://github.com/mozilla-mobile/fenix/issues/5490

**Comment by ebalazs-sv** [comment]
Verified as fixed on Google Pixel (Android Q), Samsung Galaxy S8 (Android 9), Nexus 6P (Android 8.1.0), Sony Xperia Z5 Premium (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1).
The builds from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration can replace Fennec.
I will mark this as Done.

**Comment by JohanLorenzo** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1600104 too
