### ISSUE TITLE
[Meta] Save / Autofill Basic Form Data

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5419]
This meta contains all the stories regarding saving, syncing, and auto-filling user's form data.

This is useful for mobile considering typing is more of a hassle on mobile and it will allow users to complete their tasks faster. 

**The scope for Q1 is EN-US locale.**

### Dependencies
-This depends on #5543 for the GV work.
-Having duplicates is concerning (can we merge them? we will address it in next iteration)

### User Stories

- [ ] #5492 Spike to investigate technical capabilities
- [ ]  #3277 Save Address Form Data
- [ ]  #230 Auto-fill Addresses
- [ ]  #339 Sync Addresses Data
- [ ] #6379 Form Data Management 
- [ ] #5584 [Telemetry] Basic Form Data

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13491)

**Comment by liuche** [comment]
* UI for address management (seeing, editing, deleting)
* GV will be able to autofill so no additional work will need to happen, just exposing existing GV work - this will be piggybacking off of Logins work, but additional work will be minimal
* GV first pass right now to provide just a single one
* Deduping will be a problem


Action item: we need to have UX to decide what to do, and work this out w/ GV
(will always have 2 Form autofill providers, Fenix & Google) @lime124

**Comment by madb1lly** [comment]
Hi all,
I think this is still valid as addresses and credit cards form filling is currently being tested.
Cheers 🙂

**Comment by mraonea** [comment]
2 years and form auto fill still not implemented? Wow.

**Comment by qcasey** [comment]
Stale bot don't dash my hope

**Comment by mduchev** [comment]
Still hoping...
