### ISSUE TITLE
Enable new locales in nightly

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5496]
This is primarily a L10N issue, for adding new languages.

## Dependencies
- [ ] Allow choosing Nightly-only locales #3088 
- [ ] List of locales to add from L10N

## Acceptance Criteria
* [x] Request new languages get added by L10N (languages supported on Android) and get the process documented that are missing from Fennec-parity
* [x] Add new languages to automation (should be the locales file in #3088 )
* [x] Run screenshots
* [x] Issues with these new languages are filed (related RTL support in #5497)
* [x] Define process for adding a new language to Nightly w/ L10N, as well as threshhold for promoting a language to release, and document in wiki.

This does NOT include language picker, which is #220 

## QA
- [ ] Verify that Nightly locales are not included in the release build.

**Comment by liuche** [comment]
@Delphine once we have new languages added, can we get your contributors to file new languages?

**Comment by Delphine** [comment]
Hi Liuche. Something occurred to me: as long as there is no language picker in-app, we only add new languages that we are sure are natively supported by Android to our l10n.toml file. I believe you guys just pick up what we have from there - so I'm not sure we need to add these here until a language picker is in place.
@Pike to confirm, just to make sure

**Comment by liuche** [comment]
@Delphine we're also tracking the language switcher in #220 . I think there are 2 parts, one is adding more languages supported by Android, and one is adding custom languages.

For the l10n.toml file, can we just add these if they're supported in Pontoon?

**Comment by Pike** [comment]
The process of adding new localizations to Fenix is by adding them to the config files on android-l10n, and then merge the config changes and potentially new localizations files from android-l10n into the Fenix and A-C repos.

**Comment by liuche** [comment]
As some context, here's what Axel suggested as criteria for determining locale promotion:

"For release, I'd suggest to have a process to add, and a process to remove locales from the release locales. I'd start both conversations with a threshold of translation coverage, to streamline conversations. Just to make up random numbers, it's taking > 80% to have a conversation about adding a locale to release, and < 60% to have a conversation about removing a locale.

I'm talking about conversations as I would like to add an aspect of aspiration to the decisions. We should make decisions about adding locales based on our confidence in future translation coverage, and decisions about removing locales on the lack of confidence of locales to recover in some agreed-upon timeframe. We should set limits on coverage such that these conversations are useful."

**Comment by athomasmoz** [comment]
Closing this ticket. The work to enable nightly specific locales is covered in #3088 and Delphine will call out to the community for new locales. Now that we have the language picker, we're not restricted by which locales can be enabled

**Comment by liuche** [comment]
Screenshots has an open PR
Still need to get the list of new locales from Delphine and add them

**Comment by liuche** [comment]
Talked to @Delphine, and one thing that would make it easier to move forward with this is to show all the locales in Nightly AND Preview to start with, and then based on when the final list of locales is ready, add that list before we ship.

Here's the current list of locales, and their status: https://docs.google.com/spreadsheets/d/1Z1N0a6KogjyUZQhTXFDca-0-YXBOl5Jr9xyE1fQHayE/edit#gid=0

New locales will be automatically added to Nightly through the L10N PRs!

**Comment by liuche** [comment]
Since there's nothing that we need to do here, I'm going to close this bug now, and file a follow-up for making sure to filter out the locales we want for Firefox Release.
