### ISSUE TITLE
[Meta] Download Notifications

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5582]
## User Story
As a user, I want to know the status of my download and have the ability to manage the download process so I can have control and visibility over my downloaded content. 

## Mocks
https://miro.com/app/board/o9J_kw9q71A=/

### Acceptance Criteria
- [x] System Download Notification #5959
- [x] In-app Download Notifications #5958
- [x] [Telemetry] Download notifications #5583

Done:
- [x] #1657 Integrate with GeckoView download manager
- [x] #5491 Spike for UX/eng to investigate MVP

**Comment by liuche** [comment]
@pocmo just to confirm, AC is doing any remaining download AC work (and Fenix will do the UI work to use the APIs)? I just want to make sure this is scoped for AC work (and not something that the Fenix team is expecting to pick up).

**Comment by liuche** [comment]
This is the MVP issue for shipping Downloads feature.

**Comment by brampitoyo** [comment]
@vesta0 @liuche I’ve asked our Fenix UX designers for feedback, and expect to get them by the end of the week.

This means that I’ll be ready to run through the design with you next week!

@liuche if this work has a GV component, do you know the engineer that we can contact?

Stay tuned.

**Comment by pocmo** [comment]
> @pocmo just to confirm, AC is doing any remaining download AC work (and Fenix will do the UI work to use the APIs)? I just want to make sure this is scoped for AC work (and not something that the Fenix team is expecting to pick up).

Oh, sorry, I didn't reply here yet. Additional downloads work is currently not in our list for Q4. Some of the smaller things we can definitely sneak in during our sprint (like #952). The big piece of work that I see here is saving downloads and their state to some local database so that we can surface them in the library and retry them etc. - if that is in scope for this work (my proposal is still to maybe consider handling most of those cases via the notification first).

> @liuche if this work has a GV component, do you know the engineer that we can contact?

I think there should be no additional GV work be needed. But all downloads code so far is provided by "Android Components". Ping me if you want to chat. :)

**Comment by brampitoyo** [comment]
After feedback from UX, walkthrough with @vesta0 @liuche, and further tweaks to outline behaviours and account for corner cases, I’ve arrived at a reasonable set of user flow and mockups for this feature.

Find the design under the heading **Proposed (Q4 2019)**.  This URL will always contain the latest user flow and mockups.

https://miro.com/app/board/o9J_kw9q71A=/

**Comment by vesta0** [comment]
Please close this meta once #5958 has been QA verified and closed.

**Comment by vesta0** [comment]
This feature has been completed, thank you all :)

**Comment by Poopooracoocoo** [comment]
@vesta0 
out of curiosity, why is it a no on using a determinate progress bar and why not show downloaded size/full file size?

**Comment by cadeyrn** [comment]
The notification already shows the full size. Showing the progress is #4525 and worked on in https://github.com/mozilla-mobile/android-components/issues/5284.
