### ISSUE TITLE
[Meta] Secure Proxy

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5611]
## User Story
As a user, I want my browser to keep my browsing activity and location private when I am on a public wifi, so I can keep my data safe and not be tracked.  

See [here](https://private-network.firefox.com/) for the desktop offering.

### Acceptance Criteria
I can choose to have my browser protect my browser activity and location when I am on public wifi

https://github.com/mozilla-mobile/fenix/labels/Feature%3ASecureProxy

**Broken down user stories:**

Q4 MUSTs:

- [x] Determine research plan for proxy #5731
- [x] Test current UX flow for proxy #5941
- [x]  Work with UR on research plan for proxy #5950
- [x] Create flow based on desktop requirements for proxy #5732
- [ ]  Update designs based on UR learnings #6473
- [ ] Map out full FPN UX flow #5943
- [ ] Enable and disable proxy #5747
- [ ] Show that proxy is enabled #5748
- [ ] Require account to use proxy #5750
- [ ] Proxy UI telemetry #5824

Q4 SHOULDs:

Proxy prompt on public WIFI #5751
Proxy onboarding card #5754
Onboarding blurb after update #5755

Q4 COULDs:

Proxy prompt in private mode #5753
Proxy prompt when accessing insecure site #5752

**Comment by lime124** [comment]
@topotropic can you use this ticket to bring a bit of transparency into what is happening, your activities and just general updates on the work?

feel free to create smaller GH issues to cover activities/deliverables (e.g create task flows). thanks!

**Comment by kbrosnan** [comment]
We did not end up perusing this and if we do something similar in the future a new set of issues would be best.
