### ISSUE TITLE
Integrate new TP Exceptions Management API

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5646]
### What
Add the new Exceptions Management UI for controlling ETP settings on sites

Should be merged in AC soon and then Fenix needs to integrate the new way of handling TP exceptions.
https://github.com/mozilla-mobile/android-components/pull/4554

### QA
- [ ] Verify that the 4 tracking states at the top of the [ETP SUMO article](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-preview) (blue, black, crossed out, no shield) are working as described
- [ ] Sites can be added to the exceptions list
- [ ] Sites can be removed from the exceptions list when on the site itself, through the shield icon menu toggle

**Comment by sblatz** [comment]
E1 of this work is left, we're pulling it out to run the experiment before removing the feature flag :)

**Comment by liuche** [comment]
This will be ready to go out once the experiment is finished, which I think is 11/5? (end of observation - double check w/ @mythmon )

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13110606 from 7/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20191107_123106](https://user-images.githubusercontent.com/51314259/68381671-e80be700-015a-11ea-82e6-200c2259bb01.gif)
