### ISSUE TITLE
Generic Experiment: Fenix Tracking Protection Modes - Standard vs. Strict for default

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5651]
[Link](https://experimenter.services.mozilla.com/experiments/fenix-tracking-protection-modes-standard-vs-strict-for-default/) to Experimentation Request

### Turning on the experiment
- [ ] Delete any testing/staging experiments
- [ ] Update version of experiment to match release version @glasserc

### What do we want to learn?
What should be the tracking protection default on Fenix?

### Product Questions

1- What is the impact of tracking protection on page load performance in Fenix? We already know through internal testing that content based blocking impacts page load performance by 10+%. Let's validate this in the wild.

2- Does Strict TP (linked to some page breakage) impact use engagement and retention on Fenix? We want to measure retention (primary), search count, duration, total URI count.

3- What is the right balance of usability / performance / privacy for best default tracking protection setting on Fenix?

## Hypothesis
Strict tracking Protection (content blocking) has perceptibly faster page loads than Standard Tracking Protection (cookie blocking) and that changes to the default mode will measurably impact user engagement.

We want to conduct an experiment to test this hypothesis.

## Metrics

1 - No significant (>= 2%) decrease in **retention** for moving default to Standard TP settings.

2 - No significant (>= 5%) decrease in user engagement:
- search counts
- duration (session length)
- total uri count
- user taps on the `Report Site Issue' menu option (events.browser_menu_action)

3 - Validate the assumption that strict TP impacts **page load performance** by 10+%.

### Current State

Available TP options: Standard (cookie blocking) vs Strict (content blocking)

Current mobile default is strict (content blocking with strict list) so the "standard" cohort will be downgraded in terms of TP.

### Variation A (treatment)
Tracking protection is set to 'Standard' (cookie-based tracking)
NOTE: Eng to specify how Standard branch in the code is called.

### Variation B (control)
Tracking Protection is set to 'Strict' (current default)
NOTE: Eng to specify how Strict branch in the code is called.

## Implementation Plan
- [ ] Document format for experiment and branch naming in (so future experiments can follow that format)
- [ ] Add experiments branching code to handle different experiment types
- [ ] Add QA steps (based on [this](https://github.com/mozilla-mobile/android-components/tree/master/components/service/experiments#testing-experiments) & also verifying that this doesn't happen when Experiments are opted out)
- [ ] Get all sign-offs and then submit experiment (and it will be started the following Tuesday)

## Results

To be filled out after experiment is completed.

## Conclusion

To be filled out after experiment is completed.

**Comment by liuche** [comment]
Updated the implementation steps since there weren't any.

**Comment by ekager** [comment]
I have updated the Experimenter ticket with the experiment and branch names as well as target version number

**Comment by ekager** [comment]
I have added a section to the new `experiments.md` doc about QA-ing these experiments, but reach out for help if needed!
https://github.com/mozilla-mobile/fenix/blob/master/docs/experiments.md#qa

**Comment by liuche** [comment]
We're debugging this right now but it looks like there's a problem with the server switch in AC. 

Even though we're overriding the endpoint to use staging, it's still fetching from prod.

staging: https://settings-writer.stage.mozaws.net/v1
prod: https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/mobile-experiments/records?_since=1566233826256

```
2019-10-17 15:15:34.740 6476-6542/org.mozilla.fenix.debug I/experiments: Fetching experiments from https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/mobile-experiments/records?_since=1566233826256
2019-10-17 15:15:34.741 6476-6476/org.mozilla.fenix.debug I/ExperimentsDebugActivity: Changing Kinto instance to https://settings-writer.stage.mozaws.net/v1
2019-10-17 15:15:34.794 6476-6542/org.mozilla.fenix.debug D/experiments: Fetched experiments from https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/mobile-experiments/records?_since=1566233826256:
    {"data":[]}
2019-10-17 15:15:34.795 6476-6542/org.mozilla.fenix.debug I/experiments: Experiments update from server: ExperimentsSnapshot(experiments=[Experiment(id=fenix-test-2019-08-05, description=End-to-end test of the Mobiles Experiments platform for Firefox Preview., lastModified=1566233826256, schemaModified=1566228455761, buckets=Buckets(start=0, count=667), branches=[Branch(name=a, ratio=1), Branch(name=b, ratio=1), Branch(name=c, ratio=1)], match=Matcher(appId=^org.mozilla.fenix$, appDisplayVersion=null, appMinVersion=null, appMaxVersion=null, localeLanguage=null, localeCountry=null, deviceManufacturer=null, deviceModel=null, regions=[], debugTags=[]))], lastModified=1566233826256)
2019-10-17 15:15:34.799 6476-6542/org.mozilla.fenix.debug I/experiments: onExperimentsUpdated - no experiment currently active, looking for match
2019-10-17 15:15:59.725 6476-6476/org.mozilla.fenix.debug I/ExperimentsDebugActivity: Override to the following experiment/branch:fenix-etp-5651/treatment_standard
```

**Comment by liuche** [comment]
When we turn this experiment on, we'll need to ping @travis79 or @glasserc to update the version to match the one the experiment is going out in.

**Comment by liuche** [comment]
We've asked mythmon and travis to bump the experiments version from 2.2 to 2.3. Working through #6319 which looks like a bug in the testing framework.

**Comment by liuche** [comment]
I'm going to close this issue, because this has already shipped in 2.3 release (bc QA gave us sign-off to ship)

There was a regression from some unrelated changes in the Experimenter framework regarding the versions that caused a Nightly startup crash #6441
