### ISSUE TITLE
[Meta] Bring additional Lockwise Features to the browser

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5774]
### User Story
As a user, I want to manage my Lockwise credentials for websites in my Firefox for Android Browser. 

### Acceptance Criteria

- [x] #9504 I can edit my logins in settings (completed)
- [x] #9505 I can sort my logins alphabetically (completed)
- [x] #5551 I can choose which of multiple logins I can fill 
- [x] #7094  I can choose "Never Save" on a login so that they never get prompted on that site again

**Comment by changecourse** [comment]
Does there also need to be a bullet for hide/show of password?

**Comment by liuche** [comment]
> Does there also need to be a bullet for hide/show of password?

See #5544! That will be part of basic login management, and this issue is tracking the next set of features.

**Comment by liuche** [comment]
@AmyYLee I see the option to "sort by most recently used" in the options for Logins (P4 in the top comment). I'm concerned that that would leak history in the case that
1) I visit a site that needs a login, and I autofill (which is "using" the login)
2) I clear history because I don't want that site in my history
3) I go to Logins and sort by "most recent" and then that login would show up first (because logins doesn't have a concept of "history".

**Comment by AmyYLee** [comment]
> @AmyYLee I see the option to "sort by most recently used" in the options for Logins (P4 in the top comment). I'm concerned that that would leak history in the case that
> 
>     1. I visit a site that needs a login, and I autofill (which is "using" the login)
> 
>     2. I clear history because I don't want that site in my history
> 
>     3. I go to Logins and sort by "most recent" and then that login would show up first (because logins doesn't have a concept of "history".

@liuche @ekager We can move the PIN/Biometrics authentication one level up and have this required when the user taps "Saved logins" in the Logins and passwords screen.

**Comment by abodea** [comment]
Hi, @vesta0 @liuche do you consider that it is worth adding information in Fenix regarding all the accounts saved while not being connected to the FxA?
Please note that while saving any logins while not being logged in, after connecting to the FxA everything will be synced and the accounts will be saved.
As the save login is displayed all the time when login with a new account, it can be confusing for some users as the information regarding the account being saved is not present in the app.
I added this feature request in case this will take into consideration https://github.com/mozilla-mobile/fenix/issues/9847.

**Comment by vesta0** [comment]
Thank you for filing that feature request!

**Comment by s-ankur** [comment]
Please also consider #13839 Search Logins by Username as this is also a feature available in Lockwise

**Comment by AmyYLee** [comment]
cc @violasong who will be taking over logins work

**Comment by vesta0** [comment]
The user stories outlined in this meta have been completed. Thanks team!
