### ISSUE TITLE
In-app Download Notifications

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5958]
### User Story
As a user, I want to know when my download is completed and have the ability to open my downloaded file directly from the in-app notification so I can get to my content faster and easier.

[Mocks](https://miro.com/app/board/o9J_kw9q71A=/)
[Deck](https://docs.google.com/presentation/d/11uYWSauJcqp89yCZcPoG6HBf0vJuyAMkxkXELSg0Nfo/edit#slide=id.g635b335255_3_130)

### Bugs blocking
- [x] #6434 turning wifi off
- [ ] #6615 some downloads missing filenames
- [ ] #6519 save image filenames

### Acceptance Criteria

- [x] I know when my download is completed from within the browser
- [ ] I see the filename in my in-app download notification
- [x] The download completed notification includes a link to the downloaded file
- [ ] I can open my downloaded file directly from a link on the in-app notification

**Comment by sblatz** [comment]
I’m working on #5959 and will at least partially complete this ticket through that work so I’m assigning myself.

**Comment by liuche** [comment]
Bumping this up to E8 to handle overflow work from #5959

**Comment by sblatz** [comment]
Submitted PR for this feature so that the "try again" button works: https://github.com/mozilla-mobile/android-components/pull/4954/files

**Comment by sv-ohorvath** [comment]
Removed the qa:needed label until the blocking issues are fixed.

**Comment by sblatz** [comment]
@sv-ohorvath what "blocking issues" are there for this? I think there are some bugs we have in "qa needed" for downloads, but those shouldn't block this feature from being verified.

**Comment by sv-ohorvath** [comment]
@sblatz I marked this issue as blocked by #6434 and #6576, being related to this feature. If you don't think they are blockers, we can close this issue, but the in-app notifications are not working perfectly yet.

**Comment by sblatz** [comment]
The blocking issues should be fixed. Please close this when those are closed :) @sv-ohorvath

**Comment by sv-ohorvath** [comment]
Done. Closing.
