### ISSUE TITLE
[Meta] Fenix part of Migration UI

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6233]
### User Story
As a Fennec user being upgraded to Fenix, I want to know where to find my data and understand major changes, so I can have a positive and seamless transition experience. 

### Dependencies
- [x] UX work here: [Meta] Fennec -> Fenix Transition #879 and designs should be ready by 12/9, and ready to size
- [x] Limitations and nuances from data migration should be considered

### Acceptance Criteria 
- [x] #7092 In-process migration UI
- [x] #7093 Migration Onboarding
- [x] #6980 Post-migration Onboarding

**This is part of [Meta] Fennec -> Fenix Migration User Experience #879**

**Comment by apbitner** [comment]
@vesta0 do we want to combine with https://github.com/mozilla-mobile/fenix/issues/6121 or eliminate one?

**Comment by vesta0** [comment]
@apbitner I had not seen #6121 so feel free to combine them and close one.

**Comment by vesta0** [comment]
This work has been completed and landed in nightly.
