### ISSUE TITLE
[Meta] Revisit Toolbar menu IA & feature discoverability

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#6350]
### Why/User Benefit/User Problem
As we've continued to add items to the toolbar menu, its height has increased to the point that it is scrolling on some Android devices. In addition, we should make sure important features are easily discoverable by our users, including contextual actions like Reader mode, PWA's, Open in App, etc. Let's revisit the organization of the toolbar menu to make sure users can quickly and easily find the option they're looking for.

### User Story
As a user, I want to easily and quickly find the option/action I am looking for in the toolbar menu, so I can complete my task faster. 

### Acceptance Criteria
I can easily and quickly find the option/action I am looking for.
The toolbar menu options have a clear purpose and easy to understand.
I easily know when a site is available in Reader mode
I easily know when a site can be opened with an external app (e.g. YouTube)
I easily know when a site is available as an installable Progressive Web App

Related: 
- [x] https://github.com/mozilla-mobile/fenix/issues/7276
- [x] https://github.com/mozilla-mobile/fenix/issues/6862
- [x] https://github.com/mozilla-mobile/fenix/issues/8834
- [x] https://github.com/mozilla-mobile/fenix/issues/8474

**Comment by apbitner** [comment]
We may be able to shrink the URL bar and gain some real estate in the toolbar upon completion of https://github.com/mozilla-mobile/fenix/issues/7077

**Comment by vesta0** [comment]
This work is completed :)
