### ISSUE TITLE
Turn on ETP for all users

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6354]
## User Story
We want to turn on Enhanced Tracking Protection for all users, after the experiment #5651 runs.

## Dependencies
- [x] We have decided from Experiment #5651 about what the default setting should be: the default will be _**strict**_

## Acceptance Criteria
- [ ] Remove Nightly-only feature flag for ETP
	- [ ] Remove ETP UI from Quick Settings Dialog and logic from controllers
- [ ] When the experiment #5651 is finished, set the intended default TP state (strict/standard) for all users (which will clear the experiment setting)
- [ ] Remove the experiment code added in #5651, and end exeriment on server (@mythmon)
- [x] Land Exceptions API #5646 - shield and toolbar work together
- [x] @vesta0  to decide on how to handle inability to remove a single exception via list
    - [ ] Option A: Hide Exceptions list entirely #5932
    - [x] Option B: Remove the "x" for deleting a single Exceptions item - users can still control Exception for site when on the site itself via the ETP toggle within the shield menu

### QA
- [ ] Verify that on release build 3.0 the setting *strict* is the default

Meta issue: #1749

**Comment by liuche** [comment]
@vesta0 Will we have the decision from the experiment (default is strict or standard) by the time 3.0 is ready to ship? Looking at the Experimenter guide, it looks like if the experiment runs for 21 days (7 days enrollment, 14 days observation), and we start Nov 1, it won't be ready until Nov 22.

If we won't get the results in time, some possible cases:
- we could delay the 3.0 release (this would be a good time to do the beta!)
- we could ship a 2.4
- we could ship 3.0 on time, but with whichever setting we choose (which would....not rely on the experimental data)

**Comment by vesta0** [comment]
@ekager thanks for investigating, I recommend going with Option B :)

**Comment by liuche** [comment]
Ugh, sorry I think I got confused - actually @ekager if we want this in 3.0, we should put it into the release, because it's going to be in beta anyway (and not actually released), and it can get QA-ed during the beta period 🤦‍♀

**Comment by ekager** [comment]
QA - please verify for both 3.0 and Nightly that 
1. The ETP dialog with shield in toolbar is visible and displays correctly
2. The Quick Settings dialog displays correctly 
3. The granular options for Strict/Standard display in TP Settings

**Comment by softvision-miralobontiu** [comment]
We've verified on the 3.0.0-beta.1, and on 11/08 Nightly build, the
- ETP shield dialog with is visible and is displayed correctly,
- the lock icon is displayed correctly and doesn't include TP UI,
- the granular options for Strict or Standard are displayed in Settings,
- the setting "Strict" is the default one. 
Verified with Samsung Galaxy Note 8 (Android 9), Google Pixel (Android Q).

**Comment by liuche** [comment]
@ekager update the checkboxes here, or reopen?
