### ISSUE TITLE
Allow users to bypass certificate error pages in Fenix

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6380]
## User Story
- As a user, I want to have the option to bypass certificate error pages in Fenix, so I can visit an insecure site of my choice at my own risk (e.g. a site with self-signed cert) 

## Dependencies
- [x] [GV bypass certs](https://bugzilla.mozilla.org/show_bug.cgi?id=1553265) should be ready Q1 (or even Q4!)
- [x] [AC](https://github.com/mozilla-mobile/android-components/issues/3960) bug corresponding to GV bug
- [ ] The two different cert errors  [here](https://docs.google.com/spreadsheets/d/1SIAm3XZz5uGOm39rAR1hcCje7XYOfqqfSkxnXWttBeU/edit#gid=1453201767)
- [ ] Possible dependency - making the error pages scrollable/top-nav #5892 

### Acceptance Criteria
- [ ] Investigate/prototype a native fragment implementation vs using html error pages to handle this bypass cert. If we do it natively, decided to do this in Fenix. If we want to do this natively and run into problems, ask @brampitoyo if we need updated mocks w/ toolbar.
- [ ] When I come across a site with certificate error (specifically ERROR_SECURITY_BAD_CERT), I can bypass that error and visit the site.
- [ ] Telemetry Ticket: Track how often users choose to bypass the cert error page. 

### Does not require
- [ ] View certificate - chatted w/ Bram and he said that's not a requirement here #5073 
- [ ] Updating the image for the template, that is #5892 
- GeckoView won't expose all error codes that Gecko has, and the list is [here](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebRequestError.html). 

Web compat issue for reference: https://webcompat.com/issues/34583

#### Design Work
- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility – is this a review by someone, just keeping it in mind?
- [x] For existing UI changes, deltas are highlighted: compare “Current” to “Proposed” in user flow
- [ ] Strings/content reviewed and approved (waiting for content feedback on just one specific part of this design: the “Advanced” section)
    - [x] Are they too long for the component in other locales (not an issue, since we have unlimited vertical space)

#### Deliverable
- [ ] ~Assets uploaded to Google Drive~ (No new asset)
- [x] Links to deliverables (spec, assets) posted in comment 0

### Deliverable links
- User flow: https://miro.com/app/board/o9J_kwVai6Q=/
- Spec (inspectable artboard): https://share.goabstract.com/4e41102c-a51a-470d-b9ce-bd10fad8675c
- Assets: no new asset

**Comment by liuche** [comment]
This is still a MUST because if a user can't open a webpage that the want to access, that is a reason for them to switch to another browser.

**Comment by brampitoyo** [comment]
Just a heads up that I’m thinking to work on this issue on this sprint. Stay tuned for confirmation.

**Comment by cpeterso** [comment]
This GV fix will require some Gecko (and desktop Firefox) changes, too.

**Comment by brampitoyo** [comment]
Progress report: I’ve finished the first-round user flow and mockups for this feature.

Board: https://miro.com/app/board/o9J_kwVai6Q=/

@cpeterso @vesta0 @liuche We’re now ready for a first-round Engineering walkthrough for early next week. Please let me know if there’s anybody specific that I should invite for this walkthrough. I’d be happy to take feedback at that point, or here asynchronously. Either way, the design may still change further.

**Comment by brampitoyo** [comment]
@mheubusch On the board, I’ve also paged you for content feedback on just one specific part of this design: the “Advanced” section. For the rest of the design, Content Strategy had worked through it.

**Comment by liuche** [comment]
Looks like the GV work for this won't be done until Q1.

**Comment by brampitoyo** [comment]
After walkthrough with Engineering and more revisions earlier today, the UX part of this work is now complete.

**Comment by liuche** [comment]
Some context:
- If users can't bypass errors and get to their sites, they might just switch to another browser
- According to @fluffyemily this is a significant amount of work for GV, so would like to get Product input - still need to get the GV size estimate, and if the API changes, then this could **increase the Fenix size estimate for this issue**.

**Comment by liuche** [comment]
Two concerns voiced in the certs walkthrough meeting were:
- There might be certs that Desktop doesn't allow bypassing for - these should not be part of the GV error exposed: ERROR_SECURITY_BAD_CERT
- There are multiple SSL errors - however, for now, everything is bundled up into ERROR_SECURITY_BAD_CERT with a generic error text

**Comment by liuche** [comment]
This is done in GV now, so we should decide if this will be AC-by-Fenix or has work that AC will do.

**Comment by sblatz** [comment]
This is probably way less work now that [this ac patch](https://github.com/mozilla-mobile/android-components/pull/5484) landed 😄

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that the new UI is displayed on the certificate error pages but with little differences from the mock-ups. Since the scope of this ticket is successfully displayed, but with those differences, I'll remove the qa:needed and wait for more updates about this ticket to be sure that the works are finished and this UI is the expected one, thanks.

Devices:
- Motorola Moto G6 (Android 8.0);
- LG g7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9).

Build: 
- Firefox Preview Nightly 200204 2/4.
![Screenshot_2020-02-04-10-43-39](https://user-images.githubusercontent.com/40264165/73728328-d3c88d80-473b-11ea-9652-88bc17dd4692.png)

**Comment by sblatz** [comment]
@brampitoyo and I agreed at AllHands that this UI was acceptable. Since this is the only issue found by QA I will close this as fixed :)

**Comment by sv-sdeiac** [comment]
Due to the last comment, I'll set the ticket as verified, thanks.

**Comment by liuche** [comment]
@sblatz is there a way to revoke the "Accept Risks and Continue" on sites that the bypass was accepted for? 😅

**Comment by brampitoyo** [comment]
@liuche – @sblatz can correct me if my assumption is wrong.

We reckon that we’d like to have our own certificate store, but it’s not viable for release. So for now, we’ve decided to only “allow once”, or “allow once for this session” (ie. until Fenix is quit). Yes, it’s annoying; but we’re hoping that these are issues that site authors will fix quickly – not something users need to bypass permanently.

**Comment by garrett** [comment]
@brampitoyo: Servers sometimes happen to have self-signed certificates, especially when running behind a firewall (where the server has a local name or just an IP, but not a fully qualified domain name). In these cases, it's something that does need to be bypassed permanently.

(Huge thanks to getting in a bypass at all, even if it has to be bypassed every time at the moment!)
