### ISSUE TITLE
[Meta] Add search attribution data

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#6448]
In order to get Desktop parity for search attribution, Fenix needs to add some search telemetry for counting follow-on and organic searches, as well as verify that the search access points are all covered.

### Sub-issues
- [x] Search access points #6556 
- [ ] Follow-on and Organic search #6557 
- [ ] Ad clicks and pages with ads #6558 

### Helpful context
This is a helpful [Data summary](https://docs.telemetry.mozilla.org/datasets/search.html)

Here are the [Glean telemetry types](https://mozilla.github.io/glean/book/user/metrics/index.html).

At a high level, this should include the Mobile equivalents of this Desktop telemetry:
- Histogram: [SEARCH_COUNTS](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Histograms.json#8950)
- Scalars: [`browser.search.with_ads` and `browser.search.ad_clicks`](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Scalars.yaml#4305)

The main file that is relevant here is [SearchTelemetry.jsm](https://searchfox.org/mozilla-central/source/browser/components/search/SearchTelemetry.jsm)

There are also some tests that could be helpful:
- [browser_searchTelemetry](https://searchfox.org/mozilla-central/source/browser/components/search/test/browser/browser_searchTelemetry.js)
- [test_urlTelemetry](https://searchfox.org/mozilla-central/source/browser/components/search/test/unit/test_urlTelemetry.js)
- [browser_usageTelemetry_*](https://searchfox.org/mozilla-central/search?q=path%3Abrowser_usage&case=false&regexp=false&path=)

For more details on the Desktop implementation, you can talk to Mark Banner or Mike Kaply.

**Comment by liuche** [comment]
Hey @fbertsch, could you give some thoughts as to how the corresponding Histograms and Scalars should be set up in Mobile? I don't believe we have either of those, so what should they look like? We could also ask the Glean team (cc @Dexterp37 ) what they would suggest.

@fbertsch could you also provide some sample histogram or scalar data, to get a more concrete example of what this data should look like? I assume it's going to be of the formats/examples:
- `<engine-name>.<search-access-point>`
- `google-2018.urlbar`
- `<engine-name>.alias`
- `<provider>.in-content:[sap|sap-follow-on|organic]:[code|none]` 
- `google.organic:in-content:firefox-b`
- `browser.search.ad_clicks`
- `browser.search.with_ads`

**Comment by Dexterp37** [comment]
> 
> 
> Hey @fbertsch, could you give some thoughts as to how the corresponding Histograms and Scalars should be set up in Mobile? I don't believe we have either of those, so what should they look like? We could also ask the Glean team (cc @Dexterp37 ) what they would suggest.

Hey @liuche ! We do have [both scalars and histograms](https://mozilla.github.io/glean/book/user/metrics/index.html) in the Glean SDK, they are just better scoped (e.g. counts vs uint, labeled counts vs keyed histograms) :-)

Can you list the specific Desktop metrics you're interesting in porting over to Fenix?

The ones you listed in [the first comment](https://github.com/mozilla-mobile/fenix/issues/6448#issue-517508527) can be mapped to the following types:

- [`SEARCH_COUNTS`](https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/toolkit/components/telemetry/Histograms.json#8950) is [already reported by Fenix](https://github.com/mozilla-mobile/fenix/blob/f0468f8099244095351753e897bc77e772a6609d/app/metrics.yaml#L296), with the same semantics. It's a [`labeled_counter`](https://mozilla.github.io/glean/book/user/metrics/labeled_counters.html));
- [`browser.search.with_ads`](https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/toolkit/components/telemetry/Scalars.yaml#4315) can be a [`labeled_counter`](https://mozilla.github.io/glean/book/user/metrics/labeled_counters.html));
- [`browser.search.ad_clicks`](https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/toolkit/components/telemetry/Scalars.yaml#4335) can be a [`labeled_counter`](https://mozilla.github.io/glean/book/user/metrics/labeled_counters.html));

In addition to @fbertsch, if you haven't already, I'd recommend to loop in Data Science (or data scientists working on mobile search data) for deciding what's the best shape of the data :) Ryan Harter [was working on search data before](https://bugzilla.mozilla.org/show_bug.cgi?id=1543433), but I'm not sure he's working on this anymore.

**Comment by vesta0** [comment]
Closing since the work is being tracked in broken down tickets.

**Comment by fbertsch** [comment]
@vesta0 can you link to the other tickets?

**Comment by vesta0** [comment]
See issue description:

> ### Sub-issues
> 
>     * [x]  Search access points #6556
> 
>     * [ ]  Follow-on and Organic search #6557
> 
>     * [ ]  Ad clicks and pages with ads #6558
>
