### ISSUE TITLE
[Meta] Optimize homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6602]
### User Story
As a user, I want to easily find what I need on my homescreen, so I can get to it faster without having to scroll or having to look for it.

### Action Items
- [ ] New fragment to display open tabs
- [ ] Allow navigation from the new fragment to the selected tab
- [ ] Rewire navigation from the home screen and browser screen to the new "tab tray"

### Breakout bugs
- [ ] #6190 Top Sites
- [ ] #1063 Tabs Tray

For UX:
-Based on your investigation in #5652 please create actionable tickets and link them to this meta. 
-Please consider what brings more value to users right on the homescreen? Top sites, open tabs, collections, etc?

**Please also see user feedback for collections [here](https://docs.google.com/spreadsheets/d/1_scqRuhOezFDiiTN47ir9henxSzWFQwhERoryWWcC08/edit#gid=0)**

Related homescreen issues, but not dependencies:
- [ ] https://github.com/mozilla-mobile/fenix/issues/1063
- [ ] https://github.com/mozilla-mobile/fenix/issues/955
- [ ] https://github.com/mozilla-mobile/fenix/issues/2152
- [ ] https://github.com/mozilla-mobile/fenix/issues/2735
- [ ] https://github.com/mozilla-mobile/fenix/issues/4351

**Comment by jawz101** [comment]
This is my input
https://github.com/mozilla-mobile/fenix/issues/5853

**Comment by liuche** [comment]
This is a MUST because we will need it for top sites.

**Comment by topotropic** [comment]
@liuche I briefly discussed it with @boek and will continue to discuss it with him and refine the issue, attach mocks etc

**Comment by bifleming** [comment]
@topotropic is design complete for this?

**Comment by liuche** [comment]
Nicole said the mocks are done, and since the only two issues are already on the board, we're removing the meta from the board.
