### ISSUE TITLE
[Product Quality] Private Browsing Mode - Checklist

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#6629]
**Feature Level Checklist for Private Browsing Mode**

This is an ongoing list for product quality related bugs for this feature/component. Any non-blocking UX issues should be added here (bugs that impact quality of product but do not hinder functionality or accessibility). Blocking UX bugs should be filed separately and triaged by product. Items in this list that are fixed should be checked off by UX (Engineering please ping UX owner when an item is fixed).

----------------------------------------------------
**Checklist**

- [ ] - 1. Header copy should read “Private tabs”
- [ ] - 2. Increase line spacing (leading) to 20px. Text should be 14px
- [ ] - 3. Snackbar colour should be #312A65 (same as light theme)
- [ ] - 4. Body copy should left align to header “Private session”

![PBM Edits](https://user-images.githubusercontent.com/5992746/69365922-49f04480-0c63-11ea-94d1-5a8d6a40f857.png)

**Comment by mcarare** [comment]
@AmyYLee For 5: The text was changed according to https://github.com/mozilla-mobile/fenix/issues/3604#issuecomment-539679640. Do you want to change it back to "deleted? TY!

**Comment by AmyYLee** [comment]
> @AmyYLee For 5: The text was changed according to [#3604 (comment)](https://github.com/mozilla-mobile/fenix/issues/3604#issuecomment-539679640). Do you want to change it back to "deleted? TY!

Thanks for bringing this to my attention. Please leave it as "tab closed". I'll remove it from the checklist.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build from **11/29** with **Google Pixel 3a XL(Android 10).**
