### ISSUE TITLE
[Meta] Unify back button behavior

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#6694]
We want to collect all of the odd back button behavior here

- [x] https://github.com/mozilla-mobile/fenix/issues/6304
- [x] #4904 
- [x] https://github.com/mozilla-mobile/fenix/issues/6620
- [ ] https://github.com/mozilla-mobile/fenix/issues/5727
-  [x] #6247

**Comment by brampitoyo** [comment]
@boek @ekager I saw and document another odd back button behaviour on https://github.com/mozilla-mobile/fenix/issues/6666#issuecomment-557948786

STR:

1. Tap search bar
App response: Show search modal

2. Scroll down the screen to select a search engine below the fold
App response: dismiss keyboard, show list of search engines

3. Tap back button or swipe (if on Android 10)
Expected response: Go back to Firefox Preview start screen
Actual response: Firefox Preview exits to the phone home screen ← This is an odd behaviour

**Comment by mcarare** [comment]
The only item left unchecked is waiting for a decision regarding the split of library items. See https://github.com/mozilla-mobile/fenix/issues/5727#issuecomment-585225173

**Comment by topotropic** [comment]
I commented on https://github.com/mozilla-mobile/fenix/issues/5727 and closed it – so that was everything for the meta.
