### ISSUE TITLE
[Meta] Visual problems when changing between private/normal mode

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/fenix#6801]
NOTE: we should avoid making changes to this code until #1063 lands to avoid major conflicts.

As a user, I would like cleaner transitions between private and normal browsing mode.

- [ ] Tabs briefly have incorrect colors while switching browsing mode (#6796) (+ related https://github.com/mozilla-mobile/fenix/issues/6516)
- [ ] Home title text overlaps during normal/private transition (#6797)
- [ ] "No open tabs”/private mode explanation is briefly shown when tabs exist (#6798)
- [ ] Most fade in animations happen in serial (#6799)
- [ ] Inconsistent feel between normal -> private and private -> normal (#6800)

**Comment by Baron-Severin** [comment]
It seems to me that we could fix most of these problems by somehow animating away our tabs before switching modes.  The animation could be anything (fade out, roll up, etc), as long as we somehow removed them before the theme switch.  


### Engineering notes
- Switching themes causes the activity to recreate.  We're currently trying to animate between states during that recreation, which is tricky.
- This would also cut down on the number of transitions we would need to handle.  Right now we need to be able to animate to/from the following states (many of which have their own bugs)...
```
0 normal tabs to 0 private tabs
0 normal to 1+ private
1+ normal to 0 private
1+ normal to 1+ private
0  private to 0  normal
0 private to 1+ normal
1+ private to 0 normal
1+ private to 1+ normal
```
... whereas with this change, we would only handle...
```
1+ normal to 0 normal
1+ private to 0 private

0 normal to 0 private
0 private to 0 normal
```
... which are all also much simpler animations.

**Comment by athomasmoz** [comment]
This enhancement needs UX input. Note that this will be through tab tray in future

**Comment by Baron-Severin** [comment]
We're going to work on this next week after some major changes to the home screen in #1063 #6651 land

**Comment by boek** [comment]
@vesta0 and @Baron-Severin will prioritize these issues

**Comment by Baron-Severin** [comment]
After talking with @vesta0, #6798 seems to be the highest priority.
