### ISSUE TITLE
[Meta] Reader Mode

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#74]
**Why/User Benefit/User Problem**

As a user, I want to have a clean and distraction free reading experience for long-form content (e.g. news articles)

**What / Requirements**

UX mocks: #190 
User Stories (listed below)

**Acceptance Criteria (how do I know when I’m done?)**
-Complete all user stories
-Supporting perceived speed goals (See ideas here: https://arxiv.org/pdf/1811.03661.pdf)

### GV dependencies:

- [x] [Allow embedders to load WebExtensions in GV](https://bugzilla.mozilla.org/show_bug.cgi?id=1518841)
- [ ] [Add messaging support for WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1518843)
- [ ] [GeckoView support for PageAction web-extension API](https://bugzilla.mozilla.org/show_bug.cgi?id=1530402) 

### A-C Dependencies:

https://github.com/orgs/mozilla-mobile/projects/25

**Comment by bbinto** [comment]
@Sdaswani: Need an engineer to do a  technical analysis and provide possible options

**Comment by Sdaswani** [comment]
Sure @bbinto the research should be sprint planned, feel free to decide when to have an engineer do that.

**Comment by cpeterso** [comment]
There is still debate whether Reader View should be implemented in A-C or GV.

Here is the GV bug for Reader View:
https://bugzilla.mozilla.org/show_bug.cgi?id=1509257

Here is the A-C issue for Reader View:
https://github.com/mozilla-mobile/android-components/issues/1346

Here is the R-B issue for Reader View:
https://github.com/mozilla-mobile/reference-browser/issues/152

**Comment by Sdaswani** [comment]
@pocmo is there an estimate if we implemented this in AC?

**Comment by pocmo** [comment]
Not yet. But we can start breaking the linked A-C issue down based on snorp's suggestion.

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP, however it should land for MVP as an individual feature.
