### ISSUE TITLE
[Meta] Promote Lockwise in Fenix 

### ISSUE THREAD

**Issue by sandysage** [mozilla-mobile/fenix#821]
This meta will explore how we want to promote Lockwise within Fenix

We are building basic [login management](https://github.com/mozilla-mobile/fenix/issues/1284) in Fenix in Q4 which will address most user needs. For users that may be interested in or looking for more advanced login features (e.g. password generator, create new logins, etc) we want to let them know about Lockwise and how they can benefit from additional privacy and security features. 

Related tickets for consideration:

See [here](https://docs.google.com/spreadsheets/d/1I46qnbm69KNGN02r1Ut23HbiH5oAR7YlpIdID8IXP2w/edit?ts=5dcd8371#gid=892785064) for final agreed upon use cases that we want to support. 

- [ ] #5498 If Lockwise not installed, point out that people can use Lockwise as a Login Manager 
- [ ] #550 Seamless Lockwise integration in Fenix for existing Lockwise users
- [ ] #3384 Sync settings should promote Lockwise and Monitor 

This meta will include a telemetry ticket to determine how often users choose to use Lockwise instead of native login management in Fenix.

**Comment by vesta0** [comment]
Dup of #550

**Comment by t-matsuu** [comment]
Currently, Minimum Android Version of Firefox Lockwise is 7.0 though that of Firefox Preview is 5.0.
Does this mean Fenix users on Android 5.x-6.x cannot select Mozilla-based password manager?

**Comment by liuche** [comment]
Also, see:
" The login management feature has a similar design and branding as Lockwise" from #1284 (unfiled). Not sure if this is related, but surfacing here in case it's relevant.

**Comment by vesta0** [comment]
On the surface this does not require A-C work. To be confirmed once UX is available.

**Comment by lime124** [comment]
putting the meta in the in design column as amy is in progress on work for the sub-issues.

**Comment by vesta0** [comment]
Will consider this as part of other related work.
