### ISSUE TITLE
[Meta Toolbar] Remove feature flag for dynamic bottom toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8775]
We have now enabled dynamic bottom toolbar for nightly/debug builds. Filing this so we eventually enable it for all builds.

These three issues are the most critical to verify before landing this in a wider release:

- [x] #10073 embedded content scrolling (less critical)
- [x] #10045 Dynamic toolbar not appearing
- [x] #8768 Large white space left at top/bottom
- [ ] #10477 Can't scroll almost full pages (affects error pages)
- [x] When this is ready to land, please ping @mcomella for #10157

## Top Toolbar Issues
* Note these currently exist in release.
- [ ] https://github.com/mozilla-mobile/fenix/issues/11388
- [ ] https://github.com/mozilla-mobile/fenix/issues/11389

cc @vesta0 to track this :)

**Comment by liuche** [comment]
I'll be cutting the 5.0 release on Monday 4/27 with the new AC release, @sblatz is this ready to be turned on? I believe @AmyYLee will meet and go over this with you next week to decide if we want it in the Fennec/Fenix build. In the meantime, if there aren't any large outstanding issues, @vesta0 wanted to get this onto Firefox Preview.

**Comment by sblatz** [comment]
As discussed on Slack, I think we should actually block this feature flag on these two issues (caused by the same underlying GV bug):

https://github.com/mozilla-mobile/fenix/issues/10073
and
https://github.com/mozilla-mobile/fenix/issues/10045

**Comment by liuche** [comment]
We decided that we'll remove the feature flag for 5.2 so we can get more testing on it, even though we really need #10477 to be fixed if we want to put this in The Release.

**Comment by liuche** [comment]
The remaining issue is not a release blocker.
