### ISSUE TITLE
[Meta] Fennec -> Fenix Migration User Experience

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#879]
### User Story

As a user I want to have a seamless experience as I transition from using Fennec to Fenix.

**This meta is a UX only priority for Q4.**

[A-C board](https://github.com/orgs/mozilla-mobile/projects/40) for reference on ENG work

Related issues:

- [x] #6118 Fennec to Fenix Migration User Journey / Timeline 

- [x] #6120 Fennec Migration UI 

- [x]  #6233 Fenix Part of Migration UI

- [x]  #880 Migration Notifications

@boek will be the Eng contact for this.

### UX
Miro: https://miro.com/app/board/o9J_kw1CGow=/
Fennec Abstract: https://share.goabstract.com/bf05723f-c4a4-4939-9882-f4dd6c490353?
Fenix Abstract: https://share.goabstract.com/b1b9f719-fbb5-4c94-b45d-556232a3cd52?

**Comment by vesta0** [comment]
Related issues tracked individually due to different timing.

**Comment by creesch** [comment]
Does this being added to Q4 mean that around that time Fenix will replace Fennec? I am mostly asking in relation to [this comment made a while ago](https://github.com/mozilla-mobile/fenix/issues/574#issuecomment-466980564) in #574.

**Comment by vesta0** [comment]
This meta has been completed and landed in nightly 🙌
