### ISSUE TITLE
[Meta] Pull to refresh issues

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#9766]
After enabling "pull to refresh" in https://github.com/mozilla-mobile/fenix/issues/3262 a number of issues were discovered.

Most of the issues relate to the following:
- [x] No differentiation between inner / outer level scrolls.
We should only show the throbber for top level scrolls.
GV ticket - https://bugzilla.mozilla.org/show_bug.cgi?id=1627737

- [x] For websites with their own touch handlers but which do not consume the scroll we should allow pull to refresh.
GV ticket - https://bugzilla.mozilla.org/show_bug.cgi?id=1633322
Other browsers like Fennec (based on the behavior of the AwesomeBar / overscroll effect) or Chrome correctly support this.
This needs a deeper investigation and maybe a complete rethink of how pull to refresh / dynamic toolbar works.

- [x] For websites with their own touch handlers we might show a glimpse of the throbbler.
GV - ticket - https://bugzilla.mozilla.org/show_bug.cgi?id=1631754

- [x] No actual differentiation between zooming / scrolling gestures - https://github.com/mozilla-mobile/fenix/issues/10241

- [x] "Cancel" on a repost prompt doesn't hide the throbber - https://github.com/mozilla-mobile/fenix/issues/9799

- [x] Allow users to disable gesture based features - https://github.com/mozilla-mobile/fenix/issues/10240

- [ ] Issues with google maps' bottom sheet:  
  - [x] the wrong elements scroll - [fenix tracking issue](https://github.com/mozilla-mobile/fenix/issues/16055) | [GV ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1672204)
  - [ ] rendering issues - [GV ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1679315)
  - [ ] scroll issues - [GV ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1679316)
&nbsp;
- [ ] Support more CSS and Event properties related to pull to refresh - https://bugzilla.mozilla.org/show_bug.cgi?id=1679316

- [ ] Avoid unintended refreshes - https://github.com/mozilla-mobile/fenix/issues/16577
  

&nbsp;
~As such we will disable pull to refresh until all of the above issues are resolved.~
~- [x] https://github.com/mozilla-mobile/fenix/issues/9770~

&nbsp;
With most of the issues fixed this is ready for nightly but should not get into Beta / Release until all issues are fixed.
- [x] Ticket to enable feature in Nightly/Debug - https://github.com/mozilla-mobile/fenix/pull/16060

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16708)

**Comment by abodea** [comment]
Hi, below you can find all the related bugs to the **`Pull to refresh`** feature.
| Website | Bug ID | Reproducible?  | Comments  | 
| :--: | :--: | :--: | :--: |
| **https://bing.com/covid** | **[9724](https://github.com/mozilla-mobile/fenix/issues/9720)** | ✔️  |    | 
| **Phonearena.com** | **[9720 ](https://github.com/mozilla-mobile/fenix/issues/9724)**| ✔️ |       | 
| **twitter** | **[9718 ](https://github.com/mozilla-mobile/fenix/issues/9718)**| ✔️ |       | 
| **GitHub** | **[9708 ](https://github.com/mozilla-mobile/fenix/issues/9708)**| ✔️ |       | 
| **uBlock Origin settings** | **[9715 ](https://github.com/mozilla-mobile/fenix/issues/9715)**| ✔️ |       | 
| **Bugzilla** | **[9715 ](https://github.com/mozilla-mobile/fenix/issues/9715#issuecomment-609682657)**| ✔️ |  Bugzilla bug [1415628](https://bugzilla.mozilla.org/show_bug.cgi?id=1415628)|

**Comment by caugner** [comment]
Please also consider disabling pull to refresh after the user has started to fill out a form:

1. Open https://www.caresteouvert.fr/@48.861687,2.333530,17.81/place/n4246099576
2. Select "Report a change"
3. "Select "No"
4. Type in some text
5. (Accidentally) pull down
6. Page refreshes

**Comment by abodea** [comment]
Hi @caugner thank you for the notice!
Note that I already verified the issue on the latest build you can find it here https://github.com/mozilla-mobile/fenix/issues/9770#issuecomment-610916270.
The Nightly from the Play Store will update soon and you will be able to see the change too.

**Comment by caugner** [comment]
Maybe off-topic, but would be possible to link the feature to a `about:config` flag?

**Comment by staktrace** [comment]
See also #9799 - that should be fixed too before re-enabling, and doesn't seem to be covered by the existing issues on this ticket.

**Comment by caugner** [comment]
> The Nightly from the Play Store will update soon and you will be able to see the change too.

My Nightly still pulls to refresh, despite being on the latest Play Store version. This is really frustrating, because I keep losing form input.

**Comment by cadeyrn** [comment]
Play Store updates are paused due to https://bugzilla.mozilla.org/show_bug.cgi?id=1628413.

**Comment by liuche** [comment]
@Mugurell it looks like the GV bug has been fixed, so it should be in Fenix Nightly. I can't tell if the other issue is a GV bug, but if all the fixes are ready, is this something your team could prioritize in a sprint? It will be important for PWAs to be able to refresh #204 .

**Comment by TitanNano** [comment]
@liuche PWAs can currently be refreshed via the site control notification.

**Comment by 3j9fkyahunqoxwqu** [comment]
Sorry for off-topic but please conseder making pull to refresh optional.

That is really irritating for some people with accessibility problems like me.

Thank you for all your hard working.
Stay safe.
Regards.

**Comment by abodea** [comment]
Thank you for this suggestion @3j9fkyahunqoxwqu, note that I will add a feature request regarding this.

**Comment by sblatz** [comment]
@Mugurell looks like the Bugzilla is about to land. Once it does, is there anything we need to change on the AC/Fenix side or will we get these benefits for free?

**Comment by Mugurell** [comment]
> @Mugurell looks like the [GV fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1631754#c6) is about to land. Once it does, is there anything we need to change on the AC/Fenix side or will we get these benefits for free?

I think we'll see an improvement based on that merge right away. Yay!

Updated now the top comment with the latest status.
The biggest issue atm, for both pull to refresh and the dynamic urlBar seems to be (based on https://bugzilla.mozilla.org/show_bug.cgi?id=1633322) that certain websites, big ones, have root element scroll listeners which will prevent us from correctly animating pull to refresh / urlBar.

**Comment by Mugurell** [comment]
Checked again the current status of this.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1633322 is still blocking. But it affects the pull to refresh in the same way it currently affects the bottom dynamic toolbar. On some sites the toolbar is not animated / pull to refresh won't be available.
- #10241 is ready to work on, we know what should be done.
- #9799 needs some investigations about the best solution. Requires ac/gv.
- #10240 is ready to work on pending strings from UX.

With the above fixed I think pull to refresh would be good for nightly.

**Comment by liuche** [comment]
Adding this issue to GV High Priority list for https://bugzilla.mozilla.org/show_bug.cgi?id=1633322 (and also affects bottom dynamic toolbar)

**Comment by Mugurell** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1633322 is merged in AC and looks to have resolve the same underlying issue for the dynamic bottom toolbar. 🥳

**Comment by opusforlife2** [comment]
Can this not be added as a toggle in Secret Settings?

**Comment by cadeyrn** [comment]
@opusforlife2 Why do you want a secret setting? There will be an option in the customization settings, see #10240.

**Comment by opusforlife2** [comment]
Secret settings are for _unfinished_ features. This is at 3/5 related bugs fixed.

**Comment by Mugurell** [comment]
The setting won't appear if the feature is not available. 
Pull to refresh is not live yet because there are still issues to be resolved.
The plan is to have the setting waiting to show up when pull to refresh will be enabled.

**Comment by opusforlife2** [comment]
Isn't that what secret settings are for? The first paint feature is behind a toggle, and it still has bugs to be resolved.

**Comment by cadeyrn** [comment]
It's not the same. There was a need for a setting for the "first paint feature" because user feedback was needed. For the "pull to refresh feature" the issues seems to be well known. If you really like to try it out now you only have to change the feature flag to true in the code and press the green button in Android Studio.

**Comment by foscoj** [comment]
Very nice feature, love it!
Sometimes there is an unintended refresh when I try pinch to zoom, but it is working great so far!

**Comment by Felk** [comment]
I am trying to build a website with a canvas to draw on. This requires me to prevent the pull-to-refresh. I took a look at [this stackoverflow post](https://stackoverflow.com/q/29008194/3688648) and tried the following, simultaneously:
- give the canvas the CSS directive `touch-action: none;`
- call `preventDefault()` on the touchmove event
- give the canvas and the body the CSS directive `overscroll-behavior: contain;`

Firefox nightly still performed the pull-to-refresh gesture. On Chrome adding the `touch-action: none;` directive to the canvas was sufficient to prevent pull-to-refresh gesture.

**Comment by masayuki-nakano** [comment]
>     * call `preventDefault()` on the touchmove event
> 
> Firefox nightly still performed the pull-to-refresh gesture.

As a module owner of DOM Events, I can say this is obviously a bug of Fenix because `touchmove` must be cancelable event.
https://w3c.github.io/touch-events/#list-of-touchevent-types

**Comment by masayuki-nakano** [comment]
And Gecko makes touch events cancelable except `touchcancel`.
https://searchfox.org/mozilla-central/rev/e1d1f043957191616721b9e8bf811c0aab8a203a/widget/TouchEvents.h#166

**Comment by mstange** [comment]
I've filed #16574, #16575 and #16576 on the webcompat issues enumerated in the previous comments. @Mugurell, could you please add those to the list?
I've also filed #16577 which is not strictly a webcompat issue but should help reduce accidental triggers.

**Comment by emilio** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/16574 / https://github.com/mozilla-mobile/fenix/issues/16598 on other compat issues I found.

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/fenix/issues/16577

**Comment by mstange** [comment]
Also #16661

**Comment by steffchep** [comment]
I'd be fine with just having a refresh button top-level. rather than inside the menu, tbh.

**Comment by nowshed-imran** [comment]
I have been following this thread and Home button thread for more than 1 year.
Literally every browser on the market has this feature. How does Firefox want to stay relevant in market while ignoring these?
Users care about UI and usability. Riding with geeks will keep you barely survive, but forget about thriving again.

**Comment by Grant-ed** [comment]
Does anyone know if there is any progress on this issue? This is the only reason why I am not using the release version, and I can imagine it is for other people as well.

**Comment by kelimuttu** [comment]
Related discussion on [Reddit](https://www.reddit.com/r/firefox/comments/rlo72u/will_pull_down_to_refresh_ever_come_to_the/) recently

**Comment by Kris-Kuiper** [comment]
Anyone that can tell when this will be available for stable? Been for years now..

**Comment by davidacardona** [comment]
> I'd be fine with just having a refresh button top-level. rather than inside the menu, tbh.

This should be a solution, let you optionally add the refresh button next to the address bar.

**Comment by Juraj-Masiar** [comment]
**Maybe it could be enabled in Beta?**
If it needs testing, then adding option to enable it in "**Firefox Beta for Testers**" sounds like a good start :)
_(I've been using it in Nightly for about 2 years and it works like 95%, so pretty good!)_

**Comment by kelimuttu** [comment]
Another related discussion on [Reddit](https://www.reddit.com/r/firefox/comments/ywqy6m/pull_to_refresh/) about this recently.

**Comment by davi-ro** [comment]
> **Maybe it could be enabled in Beta?** If it needs testing, then adding option to enable it in "**Firefox Beta for Testers**" sounds like a good start :) _(I've been using it in Nightly for about 2 years and it works like 95%, so pretty good!)_

Firefox Beta for Android now supports collections so you can install all kind of plugins made for the main firefox browser and  there is a plugin "Pull to Refresh" that works very well for me on android, already tested it for about 2 weeks and no major problems so far. Also thanks to collections, i could test more plugins and some of them work really well in the firefox android browser too.

**Comment by 424344** [comment]
@davi-ro 
Thanks for the info. 
I just tried searching for "pull" to add the extension to my custom collection, but it is not found.
But if I search with google I found this:
https://addons.mozilla.org/en-US/firefox/addon/firefox-pull-to-refresh/
It's just that I'm not able to add it in my custom collection.
How did you managed to add the extension?
Thanks.

**Comment by davi-ro** [comment]
Find/Add desired plugins into your custom collection, from firefox browser on pc. When using firefox on android you won't see all the addons that firefox has.

**Comment by tesmite** [comment]
#21536 and #25964 (both are same problem) are caused by this function and it has been a while since it was reported, but there is no follow-up.
This issue has occurred on many sites including GitHub, and we believe it should be resolved as soon as possible.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807071

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
