### ISSUE TITLE
[Meta] Homescreen UI

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#99]
# Requirements
- Search / web address input
- Access to menu
- Session placeholder to explain what's going to appear and what sessions are
- Private browsing toggle
- Animation into search

---
- [x] Menu and private browsing buttons (#136)
- [x] App logo (#137)
- [x] Search element (#138)
- [x] Sessions placeholder (#139)
- [ ] a11y (#140)

**Comment by boek** [comment]
- [ ] Menu and private browsing buttons
- [ ] App logo
- [ ] Search bar placeholder
- [ ] Sessions placeholder
